from __future__ import annotations

from pathlib import Path


SITE = Path(__file__).resolve().parents[1]

TOKEN_FILE = "assets/design-tokens.css"
HTML_ENTRYPOINTS = [
    "index.html",
    "search.html",
    "notes.html",
    "study.html",
    "translations.html",
    "templates/work.html",
    "templates/reading.html",
    "templates/source.html",
]
READER_CSS_FILES = [
    "assets/reader-work.css",
    "assets/static-reader.css",
    "assets/notes.css",
    "assets/study.css",
]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def read_site_file(relative_path: str) -> str:
    return (SITE / relative_path).read_text(encoding="utf-8")


def require_contains(text: str, needle: str, label: str) -> None:
    require(needle in text, f"{label} missing {needle!r}")


def js_function_body(script: str, function_name: str) -> str:
    signature = f"function {function_name}"
    start = script.find(signature)
    require(start >= 0, f"assets/reader-work.js missing {signature}")
    open_brace = script.find("{", start)
    require(open_brace >= 0, f"assets/reader-work.js malformed {signature}")
    depth = 0
    for index in range(open_brace, len(script)):
        char = script[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return script[open_brace + 1:index]
    raise AssertionError(f"assets/reader-work.js unterminated {signature}")


def require_ordered_markers(text: str, markers: list[str], label: str) -> None:
    cursor = -1
    for marker in markers:
        next_index = text.find(marker, cursor + 1)
        require(next_index >= 0, f"{label} missing ordered marker {marker!r}")
        require(next_index > cursor, f"{label} marker {marker!r} is out of order")
        cursor = next_index


def css_rule_block(css: str, selector: str, label: str) -> str:
    start = css.find(selector)
    require(start >= 0, f"{label} missing selector {selector!r}")
    open_brace = css.find("{", start)
    close_brace = css.find("}", open_brace)
    require(open_brace >= 0 and close_brace >= 0, f"{label} malformed selector block {selector!r}")
    return css[open_brace + 1:close_brace]


def check_tokens() -> None:
    tokens = read_site_file(TOKEN_FILE)
    expected_tokens = {
        "--page-background": "#d9d9d9",
        "--page-frame-background": "#eeeeee",
        "--page-frame-width": "1000px",
        "--reader-column-width": "764px",
        "--reader-background": "#ffffff",
    }
    for name, value in expected_tokens.items():
        require_contains(tokens, f"{name}: {value};", TOKEN_FILE)


def check_html_entrypoints() -> None:
    for relative_path in HTML_ENTRYPOINTS:
        html = read_site_file(relative_path)
        require_contains(html, "/assets/design-tokens.css", relative_path)
        require_contains(html, 'class="page"', relative_path)
        if relative_path == "index.html":
            require_contains(html, "번역", relative_path)
            require_contains(html, "/styles.css?v=home2", relative_path)
            require_contains(html, "/app.js?v=home9", relative_path)
        if relative_path in {"templates/reading.html", "templates/source.html"}:
            require_contains(html, "/assets/static-reader.css?v=static2", relative_path)
            require_contains(html, "자료 위치</summary>", relative_path)
            require("Path</summary>" not in html, f"{relative_path} should avoid tool-oriented path text")
        if relative_path == "templates/reading.html":
            require_contains(html, 'aria-label="읽기 화면 이동"', relative_path)
            require_contains(html, 'href="{{SOURCE_HREF}}">원문</a>', relative_path)


def check_page_frame_css(relative_path: str, css: str) -> None:
    for needle in [
        ".page {",
        "max-width: var(--page-frame-width",
        "background-color: var(--page-frame-background",
        "border: 1px solid var(--page-frame-border",
        "box-shadow: var(--page-frame-shadow",
    ]:
        require_contains(css, needle, relative_path)


def check_reader_css(relative_path: str, css: str) -> None:
    common_needles = [
        ".reader {",
        "background: var(--reader-background",
        "border: 1px solid var(--reader-border",
        "@media (max-width: 860px)",
        "width: auto;",
        "margin: 0 10px 24px;",
    ]
    for needle in common_needles:
        require_contains(css, needle, relative_path)
    if relative_path == "assets/reader-work.css":
        require_contains(css, "width: calc(100% - 64px);", relative_path)
        require_contains(css, "grid-template-columns: minmax(0, 1fr) 340px;", relative_path)
    elif relative_path == "assets/static-reader.css":
        for needle in [
            ".source-links",
            ".source-details",
            ".source-details summary",
            ".source-details[open] summary::after",
        ]:
            require_contains(css, needle, relative_path)
    else:
        require_contains(css, "width: var(--reader-column-width", relative_path)


def check_home_css() -> None:
    relative_path = "styles.css"
    css = read_site_file(relative_path)
    check_page_frame_css(relative_path, css)
    for needle in [
        ".nav-column {",
        "flex: 0 0 var(--reader-column-width",
        "background: var(--reader-background",
        "border: 1px solid var(--reader-border",
        ".reading-path-link.primary",
        ".reading-path-links",
        ".recent-work",
        ".recent-work-meta",
        ".root-links",
        ".root-link-list",
        ".category-empty-actions",
        "@media (max-width: 860px)",
    ]:
        require_contains(css, needle, relative_path)

    responsive = css.split("@media (max-width: 860px)", maxsplit=1)[1]
    for needle in [
        ".nav-column {",
        "flex: 0 1 auto;",
        "width: 100%;",
        "padding: 0 10px 24px;",
    ]:
        require_contains(responsive, needle, f"{relative_path} responsive block")


def check_home_script() -> None:
    script = read_site_file("app.js")
    for needle in [
        "START_READING_LIMIT",
        "RECENT_WORK_STORAGE_KEY",
        "START_READING_WORK_IDS",
        "START_READING_LABELS",
        "ROOT_LINK_LABELS",
        "CATEGORY_SUBTITLES",
        'nietzsche: ["M", "FW", "Za-I", "JGB", "GM", "GD"]',
        '"oshb.Gen", "oshb.Ps", "oshb.Isa", "sblgnt.Matt", "sblgnt.John", "sblgnt.Rom"',
        'kierkegaard: ["ee1", "ee2", "fb", "g", "ba", "ps"]',
        '"Group_Notebooks"',
        "Morgenröthe / 아침놀",
        "Big Typescript",
        "Philosophical Investigations",
        "function corpusLinks",
        "function uniqueLinks",
        "function startReadingLabel",
        "function startReadingTitle",
        "function rootLinkLabel",
        "function categorySubtitle",
        "function storedRecentWork",
        "function recentWorkMarkup",
        "function categoryEmptyState",
        "function hasCategoryFilters",
        'data-category-action="clear-filters"',
        "필터 지우기",
        "이어 읽기",
        'aria-label="자료 선택"',
        "읽기 시작",
        "root-link-list",
        "바로 읽기",
        "작품 찾기",
        "제목 또는 약호",
        "전체</button>",
        "원전 / 저자 / 전통",
        "linksByWorkId",
        "START_READING_WORK_IDS[corpus.id]",
        "START_READING_LIMIT",
    ]:
        require_contains(script, needle, "app.js")


def check_reader_pages_css() -> None:
    for relative_path in READER_CSS_FILES:
        css = read_site_file(relative_path)
        check_page_frame_css(relative_path, css)
        check_reader_css(relative_path, css)


def check_study_target_ui() -> None:
    script = read_site_file("assets/study.js")
    for needle in [
        "function noteManageHref",
        "원문 위치 없음",
        ">수정</a>",
    ]:
        require_contains(script, needle, "assets/study.js")

    css = read_site_file("assets/study.css")
    for needle in [
        "overflow-wrap: anywhere;",
        ".note-footer",
        ".note-footer .note-meta",
        ".note-actions",
    ]:
        require_contains(css, needle, "assets/study.css")


def check_search_ui() -> None:
    html = read_site_file("search.html")
    script = read_site_file("assets/search.js")
    css = read_site_file("assets/search.css")
    for needle in [
        "/assets/search.css?v=phase23",
        "/assets/search.js?v=phase35",
        'href="/search" aria-current="page">검색</a>',
        'href="/translations"',
        "본문 찾기",
        "번역",
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'id="searchSubmit"',
        'id="searchClear"',
        'id="searchActiveFilters"',
        'class="form-actions"',
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "search.html")
    for needle in [
        "activeSearchController",
        "activeSearchRequest",
        "setSearchBusy",
        "renderSearchPending",
        "function renderEmptySearch",
        "function renderSearchStart",
        "search-start-links",
        'aria-label="자료 선택"',
        "읽기 시작",
        "검색어를 입력하세요.",
        "검색 결과가 없습니다.",
        "검색어를 줄이거나 자료 범위를 넓혀보세요.",
        "const bodyMarkup = body ?",
        "function clearSearchFilters",
        "function updateSearchClearState",
        "function updateSearchFilterSummary",
        "function removeSearchFilter",
        "function resultGroupHeader",
        "function resultSnippet",
        "function resultSummaryNav",
        "function cleanText",
        "function corpusLabel",
        "function reviewStateLabel",
        "function displayMetaLabel",
        "Paragraph\\s+(\\d+)",
        "문단 ${paragraphMatch[1]}",
        "function resultMeta",
        "function resultCorpusMeta",
        "function resultFooter",
        "result-actions-inline",
        "result-action-read",
        "result-action-secondary",
        'aria-label="검색 결과 동작"',
        "search-results-works",
        "search-results-segments",
        "본문",
        "검색 결과 묶음",
        "search-results-notes",
        "searchClear.addEventListener",
        "activeFiltersEl.addEventListener",
        "filter-chip",
        "data-empty-action=\"clear-search\"",
        "search-skeleton",
        "activeSearchController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
        "검색을 완료하지 못했습니다.",
    ]:
        require_contains(script, needle, "assets/search.js")
    for noisy_action in [
        "Open work",
        "Open source",
        "Open target",
        "Manage note",
        "Search notes",
        "check saved notes",
        "function notesSearchHref",
        "function pluralize",
        "function compactCount",
        "function searchStatusText",
        "result-group-count",
    ]:
        require(noisy_action not in script, f"assets/search.js should not expose redundant search action {noisy_action!r}")
    for needle in [
        ".search-form.is-searching",
        ".spacer",
        "height: 136px",
        ".reader-header",
        '.toolbar a[aria-current="page"]',
        "gap: 4px 10px",
        "min-height: 24px",
        "margin-bottom: 16px",
        "padding-bottom: 10px",
        ".form-actions",
        ".secondary-action",
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".active-filters",
        ".active-filters.has-filters",
        ".filter-chip",
        ".result-summary-nav",
        ".result-summary-link",
        ".result-group-header",
        ".result-kind",
        ".result-kind.work",
        ".result-kind.segment",
        ".result-kind.note",
        ".result-title > a",
        ".result-footer",
        ".result-actions-inline",
        ".result-action-read",
        ".result-action-secondary",
        ".snippet-link",
        "grid-template-columns: minmax(0, 1fr) auto",
        "justify-content: flex-end",
        ".search-form.is-searching #searchSubmit",
        "padding-bottom: 12px",
        ".empty-state",
        ".search-start",
        ".search-start-links",
        "min-height: 42px",
        ".empty-actions",
        ".empty-actions a",
        ".search-skeleton-line",
        "@keyframes archive-spin",
        "@keyframes archive-skeleton",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/search.css")
    require("result-group-count" not in css, "assets/search.css should avoid duplicate search group counts")


def check_notes_ui() -> None:
    html = read_site_file("notes.html")
    script = read_site_file("assets/notes.js")
    css = read_site_file("assets/notes.css")
    for needle in [
        "/assets/notes.css?v=notes21",
        "/assets/notes.js?v=notes31",
        'href="/notes" aria-current="page">노트</a>',
        "노트 찾기",
        '<button id="notesSubmit" type="submit">적용</button>',
        'id="notesSubmit"',
        'id="notesClear"',
        'id="notesActiveFilters"',
        'id="notesExportTools"',
        "내보내기</summary>",
        'aria-label="노트 다운로드"',
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'class="export-tools"',
        'class="export-row"',
        'class="form-actions"',
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "notes.html")
    for needle in [
        "activeNotesController",
        "activeNotesRequest",
        "setNotesBusy",
        "notesExportTools",
        "exportTools.hidden = notes.length === 0",
        "setActionButtonBusy",
        "renderNotesPending",
        "function notesSummaryCounts",
        "function notesSummaryButton",
        "function renderNotesSummary",
        "function archiveCorpusById",
        "function corpusDisplayName",
        "function workDisplayName",
        "function noteTitle",
        "function noteContext",
        'statusEl.textContent = "";',
        "function renderNoteFooter",
        "note-footer",
        "note-danger-actions",
        "삭제</summary>",
        "삭제 확인</button>",
        "data-notes-summary-filter",
        "recentlyChangedNoteId",
        "function revealRecentlyChangedNote",
        "최근 변경된 노트",
        "최근 변경한 노트가 현재 필터에 가려져 있습니다.",
        "recentNote.scrollIntoView",
        "recentNote.focus({ preventScroll: true })",
        "function prefersReducedMotion",
        "function focusNoteEditor",
        "function resetNoteEditor",
        "noteField.setSelectionRange",
        "수정을 취소했습니다.",
        "editForm.requestSubmit",
        "function renderEmptyNotes",
        "function updateNotesListChrome",
        "form.hidden = !showTools",
        "아직 노트가 없습니다.",
        "읽을 문서 찾기",
        "function clearNotesFilters",
        "queryInput.focus();",
        "function updateNotesClearState",
        "function updateNotesFilterSummary",
        "activeFiltersEl.hidden = chips.length === 0",
        "function removeNotesFilter",
        "notesClear.addEventListener",
        "activeFiltersEl.addEventListener",
        "filter-chip",
        "data-empty-action=\"clear-filters\"",
        "notes-skeleton",
        "archiveCorpora = payload.corpora || []",
        "activeNotesController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
    ]:
        require_contains(script, needle, "assets/notes.js")
    for noisy_action in [
        "Open target",
        "Open work",
        "Manage note",
        "Edit note",
    ]:
        require(noisy_action not in script, f"assets/notes.js should keep Notes actions concise without {noisy_action!r}")
    for needle in [
        ".notes-form.is-loading",
        ".notes-form[hidden]",
        ".translations-form[hidden]",
        ".active-filters[hidden]",
        ".spacer",
        "height: 136px",
        ".reader-header",
        '.toolbar a[aria-current="page"]',
        "gap: 4px 10px",
        "min-height: 24px",
        "margin-bottom: 16px",
        "padding-bottom: 10px",
        ".form-actions",
        ".secondary-action",
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".export-tools",
        ".export-tools summary",
        ".export-tools[open] summary::after",
        ".active-filters",
        ".active-filters.has-filters",
        ".filter-chip",
        ".notes-summary-nav",
        ".notes-summary-filter",
        ".note-card.is-recent",
        ".note-card.is-recent:focus",
        ".note-card.is-editing",
        ".note-title > a",
        ".note-context",
        ".note-footer",
        ".note-footer .note-meta",
        ".note-actions a",
        ".note-danger-actions",
        ".note-danger-actions summary",
        ".note-danger-actions summary::after",
        ".note-danger-actions[open] summary::after",
        ".note-danger-actions button",
        ".note-edit-actions",
        "grid-template-columns: repeat(2, minmax(0, 1fr))",
        "justify-content: flex-end",
        "@keyframes archive-note-highlight",
        ".notes-form.is-loading #notesSubmit",
        "padding-bottom: 12px",
        ".empty-state",
        ".empty-actions",
        ".empty-actions a",
        ".notes-skeleton-line",
        ".note-actions button.is-working",
        "@keyframes archive-spin",
        "@keyframes archive-skeleton",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/notes.css")


def check_translations_ui() -> None:
    html = read_site_file("translations.html")
    script = read_site_file("assets/translations.js")
    base_css = read_site_file("assets/notes.css")
    css = read_site_file("assets/translations.css")
    for needle in [
        "/assets/notes.css?v=notes21",
        "/assets/translations.css?v=trans28",
        "/assets/translations.js?v=trans66",
        'href="/translations" aria-current="page">번역</a>',
        "번역 찾기",
        '<option value="">전체 자료</option>',
        'id="translationsListTools"',
        "필터</summary>",
        'class="filter-panel-fields translations-filter-fields"',
        '<button id="translationsSubmit" type="submit">적용</button>',
        'id="translationsSubmit"',
        'id="translationsClear"',
        'id="translationsReviewQueue"',
        'id="translationsExportTools"',
        'id="translationsExportTools" class="export-tools" hidden',
        "aria-keyshortcuts=\"Q\"",
        'id="translationsWorkOptions"',
        'id="translationsActiveFilters"',
        'id="translationsExportMarkdown"',
        'id="translationsExportJson"',
        'class="review-export-row"',
        'class="export-tools"',
        "내보내기</summary>",
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "translations.html")
    for needle in [
        "activeController",
        "activeRequest",
        "archiveCorpora",
        "LAST_CORPUS_STORAGE_KEY",
        "function rememberedCorpusId",
        "function rememberCorpusId",
        "pendingReviewQueueFocus",
        "pendingReviewQueueMessage",
        "translationsExportTools",
        "translationsListTools",
        "function hasSearchFilters",
        "listTools.open = shouldOpenTools",
        "exportTools.hidden = visible.length === 0",
        "if (!visible.length) exportTools.open = false",
        "setBusy",
        "function prefersReducedMotion",
        "renderPending",
        "function selectedCorpusArchive",
        "function archiveCorpusById",
        "function corpusDisplayName",
        "function compactWorkMeta",
        "function workDisplayName",
        "function sentenceDisplayName",
        "const bibleMatch",
        "function archiveWorkOptions",
        "function updateWorkOptions",
        "function renderEmptyRecords",
        "function updateTranslationsListChrome",
        "const inReviewQueue = isReviewQueueOnlyView()",
        "const showTools = !inReviewQueue && (count > 0 || activeFilters)",
        "form.hidden = !showTools",
        "아직 번역이 없습니다.",
        "const bodyMarkup = body ?",
        "읽을 문서 찾기",
        "function clearFilters",
        "queryInput.focus();",
        "function updateFilterSummary",
        "activeFiltersEl.hidden = chips.length === 0",
        "function removeFilter",
        "function renderSummary",
        "counts.total <= 0",
        "function visibleSummaryStates",
        "번역 상태 요약",
        "function reviewActionsVisible",
        'statusEl.textContent = "";',
        "function renderRecord",
        "function recordContext",
        "function recordGroupKey",
        "function groupedTranslationRecords",
        "reviewedCount",
        "function groupWorkUrl",
        "function groupSavedExportUrl",
        "function renderGroupActions",
        "translation-record-group-actions",
        ">읽기</a>",
        ">저장본</a>",
        "function renderRecordGroups",
        "const showGroupActions = options.showGroupActions !== false",
        "showGroupActions ? renderGroupActions(group) :",
        "showContext",
        "data-translation-record-group",
        "translation-record-group-title",
        "function visibleReviewStates",
        "showReviewBadge",
        "showReviewActions",
        "showGroupActions: !inReviewQueue",
        "record.target_label || sentenceDisplayName(record)",
        "corpusDisplayName(record.corpus_id)",
        "workDisplayName(record.corpus_id, record.work_id)",
        "translation-record-heading",
        "translation-record-kicker",
        "translation-record-context",
        "검토 상태:",
        "review-badge",
        "translation-record-title",
        "translation-record-footer",
        "aria-label=\"해설\"",
        "<h3>해설</h3>",
        "원문</summary>",
        "function generatedRecords",
        "function updateReviewQueueButton",
        "reviewQueueButton.hidden = generatedCount === 0 || isReviewQueueOnlyView()",
        'reviewQueueButton.textContent = "번역 검토"',
        "개 번역 검토",
        "reviewQueueButton.setAttribute",
        "번역 검토",
        "function focusFirstReviewQueueRecord",
        "function clearReviewTargetHighlight",
        "function openReviewQueue",
        "function visibleRecordCards",
        "function focusedRecordCard",
        "function focusRecordCard",
        "function navigateRecordFocus",
        "function triggerFocusedReviewAction",
        "function openFocusedSource",
        "function isTypingTarget",
        'event.key === "ArrowDown"',
        "aria-keyshortcuts=\"R\"",
        "aria-keyshortcuts=\"X\"",
        "aria-keyshortcuts=\"O\"",
        "data-open-source",
        "검토 필요",
        "검토할 번역이 없습니다.",
        "저장했습니다.",
        "모든 번역을 검토했습니다.",
        "function updateRecordReview",
        "function reviewActionMessage",
        "제외했습니다.",
        "검토 대상으로 되돌렸습니다.",
        "const actionMessage = reviewActionMessage(nextState)",
        "translation-record-summary-tools",
        "translation-record-summary-tools translation-record-summary",
        "data-translation-summary-filter",
        "review_state: reviewState",
        "/api/sentence-translations/export",
        "/api/sentence-translations/",
        "저장하지 못했습니다.",
        "translationsExportMarkdown",
        "translationsExportJson",
        'params.set("q", query)',
        "primary-review-action",
        "translation-more-actions",
        "<summary>제외</summary>",
        "제외 확인",
        'title="원문으로 이동"',
        "reviewActionsVisible() && visibleReviewStates(visible).size > 1",
    ]:
        require_contains(script, needle, "assets/translations.js")
    require_ordered_markers(
        js_function_body(script, "renderRecord"),
        [
            "translation-record-heading",
            "translation-record-title",
            "translation-text",
            "translation-commentary",
            "원문</summary>",
            "translation-record-footer",
            "translation-actions",
        ],
        "renderRecord review-first translation card layout",
    )
    require("Next item." not in script, "assets/translations.js should avoid redundant review queue status text")
    for needle in [
        ".translations-form",
        ".translations-filter-fields",
        ".list-tools",
        ".list-tools[hidden]",
        ".list-tools summary",
        ".list-tools summary::after",
        ".list-tools[open] summary::after",
        ".list-tools .translations-form",
        ".list-tools .export-tools",
        ".translation-record-summary-tools",
        ".translation-record-summary",
        "background: transparent",
        ".translation-review-queue",
        ".translation-review-queue:not(:disabled)",
        ".translation-review-queue:not(:disabled):hover",
        ".translation-record-card",
        ".translation-record-group",
        ".translation-record-group-title",
        ".translation-record-group-actions",
        ".translation-record-group-actions a",
        ".translation-record-group .translation-record-card:first-of-type",
        ".translation-record-card:focus",
        ".translation-record-card.is-review-target",
        ".translation-record-card.is-review-target:focus",
        "border-left: 3px solid #b00000",
        ".translation-record-card[data-review-state=\"generated\"]",
        ".translation-record-heading",
        "grid-template-columns: minmax(0, 1fr) auto",
        ".translation-record-kicker",
        "justify-self: end",
        ".translation-record-context",
        ".translation-record-kicker .review-badge",
        ".translation-record-title",
        "-webkit-line-clamp: 2",
        ".translation-record-title a",
        ".translation-record-footer",
        ".translation-source",
        ".translation-source summary",
        ".translation-source blockquote",
        ".translation-text",
        ".translation-commentary",
        ".translation-commentary h3",
        "clip: rect(0, 0, 0, 0)",
        ".translation-actions",
        ".translation-more-actions",
        ".translation-more-actions summary",
        "min-height: 26px",
        "border: 1px solid transparent",
        ".translation-more-actions summary:hover",
        "border-color: #ead0d0",
        ".translation-more-actions summary::after",
        ".translation-more-actions[open] summary::after",
        ".translation-more-actions button",
        "@media (hover: hover) and (pointer: fine)",
        ".translation-record-card:hover .translation-more-actions",
        ".translation-record-card:focus .translation-more-actions",
        ".translation-record-card:focus-within .translation-more-actions",
        ".translation-record-card.is-review-target .translation-more-actions",
        '.translation-record-card[data-review-state="generated"]:not(.is-review-target):not(:hover):not(:focus):not(:focus-within) .translation-record-footer',
        "@media (min-width: 861px)",
        ".translation-record-card.is-review-target .translation-record-footer",
        "position: sticky",
        "bottom: 8px",
        ".translation-actions .primary-review-action:not(:disabled)",
        ".translation-actions .primary-review-action:not(:disabled):hover",
        ".translation-actions button.is-working",
        "@media (prefers-reduced-motion: reduce)",
        "@media (max-width: 860px)",
        "overflow-x: auto",
        "scrollbar-width: thin",
        "max-height: 6.4em",
        "display: block;",
        "justify-content: center",
    ]:
        require_contains(css, needle, "assets/translations.css")
    render_group_body = js_function_body(script, "renderRecordGroups")
    require(
        "group.records.length" not in render_group_body,
        "assets/translations.js should not show per-group translation counts in headings",
    )
    require(
        ".translation-record-group-title strong" not in css,
        "assets/translations.css should not keep dead group count styling",
    )
    require(
        "Filters</summary>" not in html,
        "translations.html should avoid nested filter disclosures inside the Filter panel",
    )
    require(
        'class="filter-panel"' not in html,
        "translations.html should show filter fields directly once the Filter panel is open",
    )
    for needle in [
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".export-tools",
        ".export-tools summary",
        ".review-export-row",
        '.toolbar a[aria-current="page"]',
    ]:
        require_contains(base_css, needle, "assets/notes.css")


def check_study_ui() -> None:
    html = read_site_file("study.html")
    script = read_site_file("assets/study.js")
    css = read_site_file("assets/study.css")
    for needle in [
        "/assets/study.css?v=study23",
        "/assets/study.js?v=study40",
        'href="/study" aria-current="page">학습</a>',
        "저장한 노트 찾기",
        '<button id="studySubmit" type="submit">적용</button>',
        'id="studySubmit"',
        'id="studyClear"',
        'id="studyActiveFilters"',
        'id="studyOverview"',
        'class="study-overview"',
        'aria-label="학습 개요"',
        'id="studyExportTools"',
        'id="studyExportMarkdown"',
        'id="studyExportTranslations"',
        "저장한 번역</a>",
        'aria-label="학습 자료 다운로드"',
        "내보내기</summary>",
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'class="export-tools"',
        'class="export-row"',
        'class="form-actions"',
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "study.html")
    for needle in [
        "activeStudyController",
        "activeStudyRequest",
        "LAST_CORPUS_STORAGE_KEY",
        "function rememberedCorpusId",
        "function rememberCorpusId",
        "setStudyBusy",
        "studyExportTools",
        "studyExportTranslations",
        "function translationExportParams",
        "/api/sentence-translations/export",
        "reviewedTranslationCount",
        "exportTools.hidden = count === 0 && reviewedTranslationCount === 0",
        "exportTranslations.hidden = reviewedTranslationCount === 0",
        "studyOverview",
        "function translationSummaryParams",
        "function studyTranslationHref",
        "function translationActionLabel",
        "/api/sentence-translations/summary",
        "function translationStatusLink",
        "function renderStudyOverview",
        "const notesMarkup = notesLabel",
        "검토할 번역이 있습니다.",
        "저장한 번역이 있습니다.",
        "const hasOverview = noteCount > 0",
        "번역 검토",
        "번역 학습 상태",
        "저장한 번역",
        "renderStudy(payload, translationSummary)",
        "renderStudyPending",
        "function renderEmptyStudy",
        "renderEmptyStudy(translationSummary)",
        "function updateStudyListChrome",
        "form.hidden = !showTools",
        "function renderNoteFooter",
        "function archiveCorpusById",
        "function corpusDisplayName",
        "function workDisplayName",
        ">읽기</a>",
        ">노트</a>",
        "function studyCountLabel",
        "function studyGroupMeta",
        "archiveCorpora = payload.corpora || []",
        'statusEl.textContent = "";',
        "노트",
        "읽을 문서 찾기",
        "function clearStudyFilters",
        "queryInput.focus();",
        "function updateStudyClearState",
        "function updateStudyFilterSummary",
        "activeFiltersEl.hidden = chips.length === 0",
        "function removeStudyFilter",
        "studyClear.addEventListener",
        "activeFiltersEl.addEventListener",
        "filter-chip",
        "data-empty-action=\"clear-filters\"",
        "study-skeleton",
        "activeStudyController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
    ]:
        require_contains(script, needle, "assets/study.js")
    for noisy_action in [
        "Open work",
        "Edit notes",
        "Open target",
        "Edit note",
        "study-note-more-actions",
        "href=\"/notes?review_state=raw\"",
    ]:
        require(noisy_action not in script, f"assets/study.js should keep Study actions concise without {noisy_action!r}")
    for needle in [
        ".study-form.is-loading",
        ".study-form[hidden]",
        ".active-filters[hidden]",
        ".spacer",
        "height: 136px",
        ".reader-header",
        "margin-bottom: 16px",
        "padding-bottom: 10px",
        '.toolbar a[aria-current="page"]',
        "gap: 4px 10px",
        "min-height: 24px",
        ".form-actions",
        ".secondary-action",
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".export-tools",
        ".export-tools summary",
        ".export-tools[open] summary::after",
        ".active-filters",
        ".active-filters.has-filters",
        ".study-overview",
        ".study-overview[hidden]",
        ".study-overview-notes",
        ".study-overview-translations",
        ".study-overview-translations a",
        ".study-overview-translations strong",
        ".filter-chip",
        ".study-form.is-loading #studySubmit",
        "padding-bottom: 12px",
        ".group-meta",
        ".study-group-context",
        ".study-tags-panel",
        ".study-tags-panel summary",
        ".study-tags-panel[open] summary::after",
        ".study-tags",
        ".study-note + .study-note",
        ".note-title > a",
        ".note-footer",
        ".note-footer .note-meta",
        ".empty-state",
        ".empty-actions",
        ".empty-actions a",
        ".empty-actions a.empty-primary-action",
        ".study-skeleton-line",
        "@keyframes archive-spin",
        "@keyframes archive-skeleton",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/study.css")


def check_work_source_bundle_ui() -> None:
    documents = read_site_file("rendering/documents.py")
    for needle in [
        "def strip_markdown_links",
        "def strip_inert_markdown_links",
        "def clean_source_markdown_display",
        r"\[\[([^\n()]+?)\]\]\([^)]*\)",
        r"\[([^\n()]+)\]\([^)]*\)",
        r"\[\[([^\n()]+?)\]\]\(javascript:;\)",
        r"\[([^\n()]+)\]\(javascript:;\)",
        "def clean_reading_inline",
        "value = strip_markdown_links(value)",
        r"\d+\[\d+\]",
        "label = f\"문단 {paragraph_count}\"",
        'data-label="{html.escape(label, quote=True)}"',
        'aria-label="{html.escape(label, quote=True)}"',
        'aria-label="구역 링크"',
    ]:
        require_contains(documents, needle, "rendering/documents.py")

    sentence_units = read_site_file("sentence_units.py")
    require_contains(sentence_units, 'label": f"문장 {index}"', "sentence_units.py")
    require('label": f"Sentence {index}"' not in sentence_units, "sentence_units.py should use reader-language sentence labels")

    source_service = read_site_file("services/sources.py")
    for needle in [
        "clean_source_markdown_display",
        "display_text = clean_source_markdown_display(text) if is_markdown else text",
        "render_source_page_html(template, target.name, rel_path, display_text, reading_href)",
    ]:
        require_contains(source_service, needle, "services/sources.py")

    template = read_site_file("templates/work.html")
    for needle in [
        'id="copySourceBundle"',
        "citation-copy-options",
        "citation-copy-actions",
        'id="copyCitation" aria-label="인용 복사"',
        'class="citation-copy-options" aria-label="복사 옵션"',
        "복사</summary>",
        'id="copyUrl" aria-label="URL 복사"',
        'id="copySourceBundle" aria-label="원문 묶음 복사"',
        ">원문 묶음</button>",
    ]:
        require_contains(template, needle, "templates/work.html")

    script = read_site_file("assets/reader-work.js")
    for needle in [
        "function sourceBundleUrl",
        "function citationPreviewText",
        "function updateCitationPreview",
        "citationPreview.title = \"복사할 때 원문 URL이 함께 포함됩니다.\"",
        "복사할 때 원문 URL이 함께 포함됩니다.",
        "await copyText(citationText())",
        "function targetSnapshot",
        "function selectedSentenceTargetSnapshot",
        "function noteTargetForSave",
        "function noteTargetTypeLabel",
        "function noteTargetDisplayText",
        "function updateNoteTargetPreview",
        "고정된 노트 대상",
        "노트 대상",
        "고정 해제",
        "대상 고정",
        "function lockCurrentNoteTarget",
        "function unlockNoteTarget",
        "function syncTargetDependentViews",
        'new Set(["segment", "section", "paragraph", "verse"])',
        "/api/source-target",
        "/api/sentence-translation",
        "requestSentenceTranslation(false)",
        "원문 묶음은 섹션, 문단, 절 대상에서 사용할 수 있습니다.",
        "원문 묶음 URL을 복사했습니다.",
        "navigateSentence(1)",
        "updateTranslationReview(\"reviewed\", quickAction)",
        "setTranslationMode(\"reading\")",
        "gemmaRuntimeStatus",
        "gemmaRuntimeStatusText",
        "gemmaRuntimeCheckButton",
        "function setGemmaRuntimeIndicator",
        "async function checkGemmaRuntimeStatus",
        "/api/health",
        "setGemmaRuntimeIndicator(\"checking\", \"번역기 확인 중\",",
        "번역기 준비됨",
        "번역기 꺼짐",
        "번역기를 사용할 수 없습니다",
        "gemmaRuntimeCheckButton.addEventListener",
        "translationRecordsSummary",
        "function setTranslationRecordsSummary",
        "translation-records-summary-main",
        "translationRecordsSummary.title = detailLabel",
        "needs-review",
        "function updateTranslationExportLinks",
        "translationSentenceStates",
        "TRANSLATION_STATE_LABELS",
        "TRANSLATION_STATE_SHORT",
        "nextUnstudiedSentenceButton",
        "nextReviewSentenceButton",
        "continueStudyButton",
        "studyProgressText",
        "function setStudyProgress",
        "function updateStudyProgress",
        "진행 확인 중",
        "읽던 곳부터 계속",
        "첫 문장부터 시작",
        "번역 검토 필요",
        "학습 기록 준비됨",
        "모든 문장 학습 완료",
        "function translationStateCountsFromSentences",
        "translationSentenceStatesLoaded",
        "function sentenceHasTranslationState",
        "function sentenceTranslationState",
        "function nextUnstudiedSentenceIndex",
        "function firstUnstudiedSentenceIndex",
        "function continueStudySentenceIndex",
        "function nextGeneratedSentenceIndex",
        "function navigateToNextUnstudiedSentence",
        "function navigateToNextReviewSentence",
        "function continueStudy",
        "검토 계속",
        "review-generated",
        "wantsPreview",
        "기록 보기",
        "preview-session",
        "function renderStudySessionPreviewPending",
        "function sessionPreviewItems",
        "function sessionPreviewTargetId",
        "function openSessionPreviewTarget",
        "data-session-preview-target",
        "data-session-preview-toggle",
        "function toggleSessionPreviewGroup",
        "data-session-preview-copy",
        "async function copyStudySessionMarkdown",
        "기록 복사",
        "학습 기록을 복사했습니다.",
        "접기",
        "전체 ${group.querySelectorAll(\"li\").length}개 보기",
        "function renderStudySessionPreview",
        "function renderStudySessionPreviewError",
        "async function previewStudySession",
        "학습 기록이 준비되었습니다.",
        "학습 기록을 볼 수 없습니다",
        "기록 열기",
        "검토 필요",
        "모든 문장이 번역되었습니다.",
        "현재 위치 뒤에 미번역 문장이 없습니다.",
        "TRANSLATION_REVIEW_CHIP_LABELS",
        "TRANSLATION_REVIEW_CHIP_HINTS",
        "검토할 번역",
        "const reviewLabel = stateHint || stateLabel",
        "<span>원문</span>",
        "aria-label=\"${escapeHtml(reviewLabel)}\"",
        "function applySentenceTranslationState",
        "function applySentenceTranslationStates",
        "function clearSentenceTranslationStates",
        "data-translation-state-short",
        "data-translation-state-label",
        "sentence_state_count",
        "async function loadTranslationRecordsSummary",
        "/api/sentence-translations/summary",
        "저장한 번역",
        "review_state_counts",
        "function setTranslationReviewVisualState",
        "function flashTranslationReviewState",
        "function flashSentenceReviewState",
        "translationReviewFlashTimer",
        "sentenceReviewFlashTimer",
        "exportAllTranslations",
        "exportStudySession",
        "/api/study-session/export",
        "notes_review_state",
        "translation_review_state",
        "studySessionSummary",
        "function setStudySessionSummary",
        "function studySessionExportUrl",
        "function loadStudySessionSummary",
        "await loadStudySessionSummary();",
        "내보낼 수 있습니다.",
        "아직 내보낼 저장 항목이 없습니다.",
        "review_state\", \"all\"",
        "renderTranslationPending",
        "translation-pending-context",
        "translation-pending-commentary",
        "번역과 함께 해설을 준비하고 있습니다.",
        "selectedSentencePositionLabel()",
        "renderTranslationError",
        "GEMMA_RUNTIME_COMMAND",
        "function translationErrorIsRuntime",
        "text.includes(\"번역기\")",
        "function runtimeRecoveryMarkup",
        "translation-runtime-hint",
        "번역기가 꺼져 있습니다. 시작한 뒤 다시 시도하세요.",
        "번역기를 시작한 뒤 이 문장을 다시 시도하세요.",
        "translation-runtime-details",
        "시작 명령 복사",
        "translation-runtime-note",
        "PowerShell에서 한 번 실행하세요.",
        "translation-runtime-command",
        "translation-runtime-command-row",
        "data-translation-copy-runtime",
        "data-translation-check-runtime",
        "다시 확인",
        "명령 복사",
        "명령을 복사했습니다.",
        ".\\\\run_reader_with_gemma.ps1",
        "translation-error-actions",
        "translation-unavailable-copy",
        "translation-recovery-panel",
        "renderTranslationCancelled",
        "번역이 취소되었습니다.",
        "cancelTranslationRequest",
        "data-translation-cancel",
        "data-translation-retry",
        "data-translation-retry=\"${escapeHtml(retryMode)}\"",
        "다시 생성",
        "retry.dataset.translationRetry === \"regenerate\"",
        "번역 요청을 취소했습니다.",
        "번역을 저장하지 않았습니다.",
        "resetTranslationOutputScroll",
        "translationOutput.scrollTop = 0",
        "setActionButtonBusy",
        "translation-pending-result",
        "translation-pending-copy",
        "번역 준비 중",
        "번역을 다시 준비하는 중",
        "노트를 저장하지 못했습니다.",
        "renderCommentary",
        "<h3>해설</h3>",
        "renderTranslationEmptyState",
        "translation-empty-state",
        "translation-empty-copy",
        "공부할 문장을 선택하세요.",
        "syncTranslationModeDensity",
        "translationJumpNav",
        "translationResultToolbar",
        "translation-result-toolbar",
        "translation-result-toolbar translation-result-details translation-extra",
        "<span>원문</span>",
        "translation-result-kicker\">문장",
        "<h3>원문</h3>",
        "translation-result-meta",
        "translation-result-target",
        "translationOutputUsesInternalScroll",
        "scrollTranslationSectionIntoView",
        "const stickyOffset = 8",
        "data-translation-jump",
        "data-translation-section=\"translation\"",
        "data-translation-section=\"commentary\"",
        "translation-result",
        "translation-section-primary",
        "recentlyChangedNoteId",
        "노트를 저장하고 표시했습니다.",
        "setStudyPanelExpanded",
        "updateStudyPanelScrim",
        "studyPanelScrim",
        "beginStudyPanelDrag",
        "updateStudyPanelDrag",
        "finishStudyPanelDrag",
        "cancelStudyPanelDrag",
        "STUDY_PANEL_DRAG_THRESHOLD",
        "ignoreNextStudyPanelToggleClick",
        "pointerdown",
        "pointermove",
        "pointerup",
        "pointercancel",
        'event.key === "Escape"',
        "selectedSentencePositionLabel",
        "rememberRecentWork",
        "RECENT_WORK_STORAGE_KEY",
        "sentencePositionText",
        "function displayPositionLabel",
        "Paragraph\\s+(\\d+)",
        "문단 ${paragraphMatch[1]}",
        "function selectSentenceFromHash",
        "setStudyPanelExpanded(true)",
        "studyPanelToggleSummary",
        "updateStudyPanelToggleLabel",
        "문장 선택",
        "선택한 문장",
        "번역 중",
        "다시 시도 필요",
        "번역 완료",
        "const action = expanded ? \"본문으로\" : \"학습\"",
        "prefersReducedMotion",
        "sentenceScrollBlock",
        "activeTranslationController",
        "activeTranslationTargetKey",
        "pendingTranslationRegenerate",
        "selectedTranslationTargetKey",
        "이미 번역 중입니다...",
        "activeTranslationController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
        "ACTION_CONFIRM_MS",
        "pendingActionConfirmation",
        "actionConfirmationConfig",
        "armActionConfirmation",
        "handleConfirmedAction",
        'handleConfirmedAction("regenerate")',
        "다시 생성 확인",
        "한 번 더 누르면 이 번역을 새로 만듭니다.",
        "requestSentenceTranslation(true)",
        'handleConfirmedAction("reject")',
        "제외 확인",
        "한 번 더 누르면 이 번역을 제외합니다.",
        "hasPendingActionConfirmation",
        "clearActionConfirmations",
        "동작을 취소했습니다.",
        "setTranslationStatus(config.status, true)",
        "isMobileStudyLayout",
        "function visibleViewportTop",
        "function visibleViewportHeight",
        "function visibleViewportBottom",
        "studyPanelViewportHeight",
        "mobileSentenceSafeBottom",
        "adjustSentenceAboveStudyPanel",
        "keepSentenceAboveStudyPanel",
        "function handleViewportLayoutChange",
        "window.visualViewport.addEventListener",
        "window.scrollBy",
        "window.setTimeout(() => adjustSentenceAboveStudyPanel(node)",
        "behavior: prefersReducedMotion() ? \"auto\" : \"smooth\"",
        "STUDY_PANEL_STORAGE_KEY",
        "storedStudyPanelExpanded",
        "rememberStudyPanelExpanded",
        "updateSentenceContext",
        "sentence-context-item",
        "readingPosition",
        "initializeReadingPositionTracker",
        "IntersectionObserver",
        "visibleSentenceNodes",
        "requestAnimationFrame(refreshReadingPosition)",
        "readingCueTargetLine",
        "updateReadingPosition(node)",
        "readingPosition.hidden = false",
        "reading-position-main",
        "reading-position-excerpt",
        "is-selectable-cue",
        "현재 읽는 위치: ${label}. ${excerpt}",
        "function studyReadingCueSentence",
        "data-reading-cue-select",
        "readingPosition.addEventListener",
        "function renderTranslationTarget",
        "문장을 선택하세요.",
        "function selectedSentenceIsVisible",
        "function updateTranslationTargetViewState",
        "translationTarget.dataset.sourceState",
        "status.dataset.sourceState",
        "jumpButton.classList.toggle(\"is-source-away\"",
        "function focusSelectedSourceSentence",
        "function flashSourceFocus",
        'event.key.toLowerCase() === "s"',
        "translation-target-excerpt",
        "data-selected-source-jump",
        'aria-keyshortcuts="S"',
        "화면 안",
        "화면 밖",
        "원문이 화면 밖에 있음",
        "NOTE_DRAFT_STORAGE_KEY",
        "noteDraftPayload",
        "readerSessionStorage",
        "saveNoteDraft",
        "locked_target",
        "restoreNoteDraft",
        "clearNoteDraft",
        "sessionStorage",
        "노트 초안을 복원했습니다.",
        "노트 대상을 고정했습니다.",
        "노트 대상이 선택 문장을 따라갑니다.",
        "const target = noteTargetForSave()",
        "noteSort",
        "noteFilterClear",
        "function updateNoteFilterClearState",
        "function clearNoteFilter",
        "노트 필터를 지웠습니다.",
        "function normalizedNoteReviewState",
        "function noteReviewLabel",
        "function noteReviewAction",
        "function noteReviewActionLabel",
        "noteListSummary",
        "function sortedNotes",
        "function renderNotesPending",
        "function noteListSummaryText",
        "function renderNotesUnavailable",
        "function syncNotesFilterToolsVisibility",
        "notesFilterTools.hidden = !showTools",
        "function renderNotesList",
        "function revealRecentNote",
        "최근 변경된 노트",
        "최근 변경한 노트가 현재 필터에 가려져 있습니다. 필터를 지우면 볼 수 있습니다.",
        "recentNote.focus({ preventScroll: true })",
        "이 필터에 맞는 노트가 없습니다.",
        "data-notes-empty-action=\"clear-filter\"",
        "function noteTargetHref",
        ">원문</a>",
        "note-danger-actions",
        "<summary>삭제</summary>",
        "delete-note",
        "저장",
        "다시 열기",
        "mark-reviewed-note",
        "mark-raw-note",
        "notes-list-skeleton",
        "아직 노트가 없습니다.",
        "노트를 사용할 수 없습니다.",
        "function syncConceptsPanelAvailability",
        "conceptsTab.hidden = true",
        'conceptsTab.classList.remove("active")',
        "function visibleStudyTabs",
        "copyStudyCard",
        "function translationNoteDraftText",
        "function focusNoteComposer",
        "function noteAlreadyIncludesDraft",
        "function updateNoteReview",
        "이미 이 노트에 있습니다.",
        "이미 노트에 있습니다.",
        "noteForm.scrollIntoView",
        "preventScroll: isMobileStudyLayout()",
        "저장할 준비가 되었습니다.",
        "노트에 저장할 준비가 되었습니다.",
        "이 노트에 추가했습니다. 확인 후 저장하세요.",
        "노트에 추가했습니다.",
        "noteText.setSelectionRange",
        "translationStudyCardText",
        "function translationQuickActions",
        "function focusNextSentenceAction",
        "nextAction.focus({ preventScroll: true })",
        "translation-reading-actions",
        "translation-secondary-actions",
        "translation-secondary-actions-body",
        "저장/메모",
        "data-translation-quick-action=\"next-sentence\"",
        "다음 문장을 선택하고 번역",
        "번역 저장",
        "번역으로 메모 추가",
        "다음 문장",
        "translation-quick-actions translation-extra",
        "data-translation-quick-action",
        "이어 읽기",
        "저장",
        "메모 추가",
        "translation-target-label\">원문",
        "클립보드 복사에 실패했습니다",
        "function revealFreshTranslationResult",
        "has-fresh-result",
        "just-studied",
        'target?.closest?.(".study-page")',
        "activateStudyTabByIndex",
        "ensureActiveStudyTabVisible",
        "scrollIntoView({",
        "inline: \"nearest\"",
        "studyPage.scrollTop = 0",
        "function studyPanelStickyOffset",
        "studyPage.scrollTo({ top, behavior })",
        "section.scrollIntoView({ block: \"start\", inline: \"nearest\", behavior })",
        "aria-selected",
        "panel.hidden = !active",
        'event.key === "ArrowRight"',
        'event.key === "Home"',
    ]:
        require_contains(script, needle, "assets/reader-work.js")

    static_pages = read_site_file("rendering/static_pages.py")
    for needle in [
        "def source_mode_links",
        '<a href="/">아카이브</a>',
        ">읽기</a>",
    ]:
        require_contains(static_pages, needle, "rendering/static_pages.py")
    for noisy_text in [
        "Reading mode",
        "Personal Archive of Literature</a>",
    ]:
        require(noisy_text not in static_pages, f"rendering/static_pages.py should avoid static-reader header text {noisy_text!r}")
    require_ordered_markers(
        js_function_body(script, "updateCitationPreview"),
        [
            "citationPreviewText()",
            "citationPreview.textContent = preview",
            "복사할 때 원문 URL이 함께 포함됩니다.",
        ],
        "updateCitationPreview screen preview stays shorter than copied citation",
    )
    require_ordered_markers(
        js_function_body(script, "renderTranslationEmptyState"),
        [
            '<section class="translation-section translation-section-primary"',
            'data-translation-section="translation"',
            "translation-empty-copy",
        ],
        "renderTranslationEmptyState quiet empty layout",
    )
    for function_name, commentary_marker, trailing_marker in [
        ("renderTranslationPending", '<section class="translation-section translation-commentary translation-pending-commentary"', "translation-loading-actions"),
        ("renderTranslationError", '<section class="translation-section translation-commentary"', "translation-recovery-panel"),
        ("renderTranslationCancelled", '<section class="translation-section translation-commentary"', "translation-recovery-panel"),
        (
            "renderTranslationRecord",
            "${renderCommentary(record.commentary || record.interpretation || \"\")}",
            "${translationResultToolbar(record, cached, reviewState)}",
        ),
    ]:
        markers = [
            '<section class="translation-section translation-section-primary"',
            'data-translation-section="translation"',
            commentary_marker,
        ]
        if "translation-commentary" in commentary_marker:
            markers.append('data-translation-section="commentary"')
        if trailing_marker:
            markers.append(trailing_marker)
        require_ordered_markers(
            js_function_body(script, function_name),
            markers,
            f"{function_name} reading-first translation layout",
        )
    require_contains(template, "/assets/reader-work.js?v=common158", "templates/work.html")
    require_contains(template, "/assets/reader-work.css?v=common117", "templates/work.html")
    for needle in [
        '<div class="meta-line">{{HEADER_META}}</div>',
        'aria-label="읽기 화면 이동"',
        "reading-desk",
        "toolbar-more",
        "toolbar-more-links",
        "작업</summary>",
        'href="/notes?corpus_id={{CORPUS_ID}}&work_id={{WORK_ID}}">노트</a>',
        'href="/study?corpus_id={{CORPUS_ID}}&work_id={{WORK_ID}}">학습</a>',
        'href="/translations?corpus_id={{CORPUS_ID}}&work_id={{WORK_ID}}">번역</a>',
        'href="{{SOURCE_HREF}}">원본</a>',
        "source-page",
        "study-page",
        "studyCompanionPanel",
        "studyPanelToggle",
        "studyPanelScrim",
        "학습 패널 닫기",
        "study-panel-toggle-action",
        "study-panel-toggle-summary",
        "gemmaRuntimeStatus",
        "gemmaRuntimeStatusText",
        "gemmaRuntimeCheck",
        "번역기 상태",
        ">번역기 확인 중</span>",
        "문장을 선택하세요.",
        "translationRecordsSummary",
        "studyProgress",
        "studyProgressText",
        "진행 확인 중",
        "continueStudy",
        "이어 읽기",
        "저장된 번역 없음</div>",
        "translation-review-tools",
        "translation-review-tools-body",
        "translation-export-tools",
        'aria-label="학습 자료 내보내기"',
        "translation-export-links",
        'aria-label="다운로드 링크"',
        "내보내기</summary>",
        "exportAllTranslations",
        "전체 번역",
        "exportStudySession",
        "학습 기록",
        "studySessionSummary",
        "내보낼 항목 없음</div>",
        "aria-label=\"학습. 문장 선택\"",
        'aria-controls="studyCompanionPanel"',
        'aria-labelledby="translationCardTitle"',
        'id="translationCardTitle"',
        'class="visually-hidden"',
        "readingPosition",
        "현재 읽는 위치",
        'class="reading-position" aria-label="현재 읽는 위치" hidden',
        "{{TOC}}",
        "noteTargetPreview",
        "lockNoteTarget",
        "대상 고정",
        "메모 작성...",
        "대상</summary>",
        "note-target-body",
        'aria-pressed="false"',
        "note-options",
        "노트 태그",
        "태그</summary>",
        'aria-label="노트 저장"',
        "noteTags",
        "notes-filter-tools",
        "저장된 노트와 필터",
        "저장됨</summary>",
        "notes-list-tools",
        "noteListSummary",
        "noteSort",
        "noteFilterClear",
        "필터 지우기",
        "aria-busy=\"false\"",
        'aria-describedby="noteStatus"',
        "sentence-context-tools",
        "주변 문장",
        "문맥</summary>",
        "sentenceContext",
        "sentence-more-controls",
        "추가 문장 동작",
        "더보기</summary>",
        "sentence-more-controls-body",
        'role="tablist"',
        'role="tab"',
        'role="tabpanel"',
        "study-tab-secondary",
        'aria-controls="study-panel-translation"',
        'aria-labelledby="study-tab-translation"',
        'aria-selected="true"',
        'tabindex="-1"',
        "aria-label=\"번역 결과\"",
        "tabindex=\"0\"",
        "aria-keyshortcuts=\"ArrowUp K\"",
        "aria-keyshortcuts=\"ArrowDown J\"",
        "copyStudyCard",
        "translation-card",
        "translation-utility",
        "학습 옵션",
        "translation-utility-group",
        "translation-utility-group-label",
        'class="translation-utility-group-label visually-hidden"',
        "보기 설정",
        "보기",
        "번역 표시 방식",
        "문장 이동",
        "학습 흐름",
        "도구</summary>",
        "translation-review-duplicate-action",
        "<span>옵션</span>",
        "study-tabs",
        "previousSentence",
        "nextUnstudiedSentence",
        "미번역",
        "nextReviewSentence",
        "검토",
        "markTranslationReviewed",
        'title="번역 다시 생성"',
        'aria-label="번역 제외"',
        'aria-label="학습 노트 복사"',
        'aria-label="번역으로 메모 추가"',
    ]:
        require_contains(template, needle, "templates/work.html")

    css = read_site_file("assets/reader-work.css")
    work_markup = read_site_file("rendering/work_markup.py")
    require_contains(work_markup, "<summary>목차</summary>", "rendering/work_markup.py")
    require("Contents (" not in work_markup, "rendering/work_markup.py should keep TOC summary quiet")
    mobile_css = css.split("@media (max-width: 860px)", maxsplit=1)[1]
    mobile_page_before = css_rule_block(mobile_css, ".page::before", "assets/reader-work.css mobile block")
    for needle in [
        "width: 100%;",
        "background-size: auto var(--header-portrait-height, 128px);",
    ]:
        require_contains(mobile_page_before, needle, ".page::before mobile overflow guard")

    for needle in [
        ".reading-desk",
        ".toolbar-more",
        "flex: 0 0 auto",
        ".toolbar-more[open]",
        ".toolbar-more summary",
        "gap: 4px 10px",
        "min-height: 24px",
        ".toolbar-more summary::-webkit-details-marker",
        ".toolbar-more summary::after",
        ".toolbar-more[open] summary::after",
        ".toolbar-more-links",
        ".toolbar-more[open] .toolbar-more-links",
        ".visually-hidden",
        "grid-template-columns: minmax(0, 1fr) 340px",
        "gap: 20px",
        ".source-page",
        "padding-right: 20px",
        ".study-page",
        ".page::before",
        "background-size: auto var(--header-portrait-height, 128px)",
        ".study-panel-scrim",
        ".study-panel-scrim[hidden]",
        "background: rgba(238, 238, 238, 0.42)",
        "position: sticky;",
        "position: fixed;",
        "top: auto;",
        ".reader-sentence.loading",
        ".reader-sentence.has-translation-state::after",
        ".reader-sentence[data-translation-state=\"reviewed\"]",
        ".reader-sentence[data-translation-state=\"reviewed\"]::after",
        "content: \"✓\"",
        ".reader-sentence[data-translation-state=\"rejected\"]::after",
        ".reader-sentence.review-state-changed",
        ".translation-card[data-review-state=\"generated\"]",
        ".translation-card[data-review-state=\"reviewed\"]",
        ".translation-card[data-review-state=\"rejected\"]",
        ".translation-card.reading-mode[data-review-state]",
        ".translation-card.review-state-changed",
        ".translation-utility",
        ".translation-utility summary",
        ".translation-utility summary::-webkit-details-marker",
        ".translation-utility summary::after",
        ".translation-utility[open] summary::after",
        ".translation-utility-body",
        ".translation-utility-group",
        ".translation-utility-group + .translation-utility-group",
        ".translation-utility-group-label",
        ".translation-utility .mode-toggle",
        ".sentence-context-tools",
        ".sentence-context-tools[hidden]",
        ".sentence-more-controls",
        ".sentence-more-controls-body",
        ".sentence-context-tools summary",
        ".sentence-more-controls summary",
        ".sentence-context-tools summary::-webkit-details-marker",
        ".sentence-more-controls summary::-webkit-details-marker",
        ".sentence-context-tools summary::after",
        ".sentence-more-controls summary::after",
        ".sentence-context-tools[open] summary::after",
        ".sentence-more-controls[open] summary::after",
        ".translation-review-tools",
        ".translation-review-tools summary",
        ".translation-review-tools[open] summary::after",
        ".translation-review-tools-body",
        ".translation-review-state[data-review-state=\"generated\"]",
        ".translation-review-state[data-review-state=\"reviewed\"]",
        ".translation-review-state[data-review-state=\"rejected\"]",
        ".sentence-controls",
        "grid-template-columns: repeat(2, minmax(0, 1fr))",
        "#regenerateSentence",
        "grid-column: 1 / -1",
        "#nextUnstudiedSentence",
        "#nextReviewSentence",
        ".study-tabs",
        "grid-template-columns: minmax(0, 1.35fr) minmax(0, 1fr) repeat(2, minmax(58px, 0.78fr))",
        ".study-tab:focus-visible",
        ".study-tab.active::after",
        ".study-tab-secondary",
        ".study-tab-secondary.active",
        ".runtime-status",
        ".runtime-status-dot",
        ".runtime-status-text",
        ".runtime-status[data-runtime-state=\"ready\"]",
        "display: none",
        ".runtime-status[data-runtime-state=\"offline\"]",
        ".translation-records-summary",
        ".translation-records-summary[data-records-state=\"has-records\"]",
        ".translation-records-summary[data-records-state=\"needs-review\"]",
        ".study-progress",
        ".study-progress[data-progress-state=\"active\"]",
        ".study-progress[data-progress-state=\"complete\"]",
        ".study-progress[data-progress-state=\"review\"]",
        ".translation-export-tools",
        ".translation-export-tools summary",
        ".translation-export-tools summary::-webkit-details-marker",
        ".translation-export-tools summary::after",
        ".translation-export-tools[open] summary::after",
        ".translation-export-links",
        ".translation-export-link",
        ".translation-export-link.is-empty",
        ".study-session-summary",
        ".study-session-summary[data-session-state=\"has-content\"]",
        ".sentence-controls button.needs-confirm",
        ".translation-review-actions button.needs-confirm",
        ".translation-review-actions .translation-review-duplicate-action",
        "min-height: 38px",
        "grid-template-columns: minmax(104px, 1.35fr) minmax(80px, 1fr) repeat(2, minmax(68px, 0.78fr))",
        "overscroll-behavior-x: contain",
        "scrollbar-width: thin",
        "@keyframes archive-panel-in",
        ".study-panel.active",
        "animation: archive-panel-in 140ms ease-out both",
        ".translation-output.reading-mode .translation-extra",
        ".translation-target-main",
        ".translation-target-status",
        ".translation-target-status::before",
        ".translation-target-status[data-source-state=\"visible\"]::before",
        ".translation-target-status[data-source-state=\"away\"]",
        ".translation-target-excerpt",
        ".translation-target.is-source-visible",
        ".translation-target.is-source-away",
        ".translation-target button",
        ".translation-target button.is-source-away",
        ".runtime-status button",
        ".translation-review-actions",
        ".translation-review-actions button",
        ".reader-sentence.source-focus",
        "@keyframes archive-source-focus",
        ".translation-result",
        ".translation-empty-state",
        ".translation-empty-state .translation-section-primary",
        ".translation-empty-state .translation-section h3",
        ".translation-output .translation-empty-copy",
        ".translation-reading-actions",
        ".translation-reading-actions button",
        ".translation-reading-actions button[data-translation-quick-action=\"next-sentence\"]",
        ".translation-reading-actions button[data-translation-quick-action=\"next-sentence\"]:not(:disabled)",
        ".translation-reading-actions .translation-quick-state",
        ".translation-secondary-actions",
        ".translation-secondary-actions summary",
        ".translation-secondary-actions-body",
        ".translation-pending-result",
        ".translation-pending-copy",
        ".study-session-preview",
        ".study-session-preview-header",
        ".study-session-preview-actions",
        ".study-session-preview-counts",
        ".session-preview-group",
        ".session-preview-group.is-collapsed .session-preview-extra",
        ".session-preview-list",
        ".session-preview-list button",
        ".session-preview-toggle",
        ".session-preview-empty",
        ".translation-result-toolbar",
        ".translation-result-toolbar summary",
        ".translation-result-toolbar summary::-webkit-details-marker",
        ".translation-result-toolbar summary::after",
        ".translation-result-toolbar[open] summary::after",
        ".translation-result-detail-body",
        ".translation-result-meta",
        ".translation-result-kicker",
        ".translation-result-target",
        ".translation-jump-nav",
        ".translation-section.is-jump-target",
        ".translation-section",
        ".translation-result > .translation-section:first-child",
        ".translation-section h3",
        ".translation-card > .translation-output",
        ".translation-section-primary",
        ".translation-section-primary h3",
        ".translation-output.reading-mode .translation-section-primary h3",
        ".translation-source-detail p",
        ".translation-empty-state .translation-primary",
        "border-left: 3px solid #b00000",
        "max-height: clamp(220px, 42vh, 520px)",
        "line-height: 1.7",
        "line-height: 1.76",
        ".translation-output.reading-mode .translation-commentary",
        "border-top-color: #e6e6e6",
        ".translation-output.reading-mode .translation-commentary h3",
        ".translation-output.reading-mode .translation-commentary p",
        "line-height: 1.68",
        ".translation-loading",
        ".translation-loading-copy",
        ".translation-pending-context",
        ".translation-pending-commentary",
        ".translation-loading-actions",
        ".translation-loading-actions button",
        ".translation-study-skeleton",
        ".translation-skeleton-block",
        ".translation-skeleton-heading",
        ".translation-skeleton-line",
        ".translation-card.is-loading::before",
        "@keyframes archive-loading-rail",
        "@keyframes archive-review-confirm",
        "@keyframes archive-review-reject",
        "@keyframes archive-sentence-review-confirm",
        "@keyframes archive-sentence-review-reject",
        ".translation-cancelled",
        ".translation-cancelled button",
        ".translation-result.translation-error",
        ".translation-result.translation-cancelled",
        ".translation-unavailable-copy",
        ".translation-recovery-panel",
        ".translation-recovery-panel .translation-runtime-hint",
        ".translation-result.translation-cancelled button",
        ".translation-runtime-hint",
        ".translation-runtime-details",
        ".translation-runtime-details summary",
        ".translation-runtime-details[open] summary",
        ".translation-runtime-note",
        ".translation-runtime-command",
        ".translation-runtime-command-row",
        ".translation-runtime-command-row button",
        ".translation-error-actions",
        ".research-card button.is-working",
        ".note-item.is-recent",
        ".note-item.is-recent:focus",
        ".note-item-title",
        ".note-item-title .review-badge",
        ".note-item-title .review-badge.reviewed",
        ".note-danger-actions",
        ".note-danger-actions summary",
        ".note-danger-actions summary::after",
        ".note-danger-actions[open] summary::after",
        ".note-danger-actions button",
        "@keyframes archive-note-highlight",
        ".study-panel-toggle",
        ".study-panel-toggle::before",
        ".study-panel-toggle-action",
        ".study-panel-toggle-summary",
        "grid-template-rows: 4px auto",
        "grid-template-columns: minmax(0, 1fr) auto",
        "min-height: 34px",
        "text-overflow: ellipsis",
        ".study-page.is-expanded",
        ".study-page.is-dragging",
        ".study-page:not(.is-expanded) .study-tabs",
        "env(safe-area-inset-bottom, 0px)",
        "scroll-padding-top: 100px",
        "top: 46px",
        "scroll-padding-bottom: calc(72px + env(safe-area-inset-bottom, 0px))",
        ".study-page.is-expanded .study-panel-toggle",
        ".study-page.is-expanded .study-panel.active",
        ".study-page.is-expanded .translation-card",
        ".study-page.is-expanded .translation-output",
        "padding-bottom: calc(28px + env(safe-area-inset-bottom, 0px))",
        "overscroll-behavior: contain",
        "touch-action: pan-y",
        "touch-action: none",
        "user-select: none",
        "max(10px, env(safe-area-inset-right, 0px))",
        "max-height: min(68vh, calc(100dvh - 48px))",
        "scroll-margin-block",
        ".sentence-context",
        ".reading-position",
        ".reading-position[hidden]",
        ".reading-position.is-selectable-cue",
        ".reading-position-main",
        ".reading-position-excerpt",
        ".reading-position button",
        ".reading-position-current",
        ".reader-sentence.reading-cue",
        ".citation-copy-options",
        ".citation-copy-options summary",
        ".citation-copy-options summary::-webkit-details-marker",
        ".citation-copy-options summary::after",
        ".citation-copy-options[open] summary::after",
        ".citation-copy-actions",
        ".note-options",
        ".note-options summary",
        ".note-options summary::-webkit-details-marker",
        ".note-options summary::after",
        ".note-options[open] summary::after",
        ".note-target-tools",
        ".note-target-tools summary",
        ".note-target-tools summary::-webkit-details-marker",
        ".note-target-tools summary::after",
        ".note-target-tools[open] summary::after",
        ".note-target-body",
        ".note-target-preview",
        ".note-target-preview.is-locked",
        ".note-target-lock",
        ".notes-filter-tools",
        ".notes-filter-tools summary",
        ".notes-filter-tools summary::-webkit-details-marker",
        ".notes-filter-tools summary::after",
        ".notes-filter-tools[open] summary::after",
        ".notes-list-tools",
        ".note-filter-clear",
        ".note-list-summary",
        ".notes-list-skeleton",
        ".notes-empty",
        ".notes-empty-actions",
        ".note-target-link",
        ".research-card .sentence-context-item",
        "overscroll-behavior: contain",
        "scrollbar-gutter: stable",
        "@media (min-width: 861px)",
        ".study-page .translation-output",
        "overflow: visible",
        ".translation-output.reading-mode .translation-reading-actions",
        "position: sticky",
        "bottom: 8px",
        "will-change: transform",
        ".translation-output:focus-visible",
        ".translation-quick-actions",
        ".translation-quick-actions button",
        ".translation-quick-state",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/reader-work.css")


def main() -> None:
    check_tokens()
    check_html_entrypoints()
    check_home_css()
    check_home_script()
    check_reader_pages_css()
    check_study_target_ui()
    check_search_ui()
    check_notes_ui()
    check_translations_ui()
    check_study_ui()
    check_work_source_bundle_ui()
    print("layout contracts ok")


if __name__ == "__main__":
    main()
