from __future__ import annotations

from pathlib import Path


SITE = Path(__file__).resolve().parents[1]

TOKEN_FILE = "assets/design-tokens.css"
HTML_ENTRYPOINTS = [
    "index.html",
    "search.html",
    "notes.html",
    "study.html",
    "translations.html",
    "templates/work.html",
    "templates/reading.html",
    "templates/source.html",
]
READER_CSS_FILES = [
    "assets/reader-work.css",
    "assets/static-reader.css",
    "assets/notes.css",
    "assets/study.css",
]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def read_site_file(relative_path: str) -> str:
    return (SITE / relative_path).read_text(encoding="utf-8")


def require_contains(text: str, needle: str, label: str) -> None:
    require(needle in text, f"{label} missing {needle!r}")


def js_function_body(script: str, function_name: str) -> str:
    signature = f"function {function_name}"
    start = script.find(signature)
    require(start >= 0, f"assets/reader-work.js missing {signature}")
    open_brace = script.find("{", start)
    require(open_brace >= 0, f"assets/reader-work.js malformed {signature}")
    depth = 0
    for index in range(open_brace, len(script)):
        char = script[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return script[open_brace + 1:index]
    raise AssertionError(f"assets/reader-work.js unterminated {signature}")


def require_ordered_markers(text: str, markers: list[str], label: str) -> None:
    cursor = -1
    for marker in markers:
        next_index = text.find(marker, cursor + 1)
        require(next_index >= 0, f"{label} missing ordered marker {marker!r}")
        require(next_index > cursor, f"{label} marker {marker!r} is out of order")
        cursor = next_index


def css_rule_block(css: str, selector: str, label: str) -> str:
    start = css.find(selector)
    require(start >= 0, f"{label} missing selector {selector!r}")
    open_brace = css.find("{", start)
    close_brace = css.find("}", open_brace)
    require(open_brace >= 0 and close_brace >= 0, f"{label} malformed selector block {selector!r}")
    return css[open_brace + 1:close_brace]


def check_tokens() -> None:
    tokens = read_site_file(TOKEN_FILE)
    expected_tokens = {
        "--page-background": "#d9d9d9",
        "--page-frame-background": "#eeeeee",
        "--page-frame-width": "1000px",
        "--reader-column-width": "764px",
        "--reader-background": "#ffffff",
    }
    for name, value in expected_tokens.items():
        require_contains(tokens, f"{name}: {value};", TOKEN_FILE)


def check_html_entrypoints() -> None:
    for relative_path in HTML_ENTRYPOINTS:
        html = read_site_file(relative_path)
        require_contains(html, "/assets/design-tokens.css", relative_path)
        require_contains(html, 'class="page"', relative_path)
        if relative_path == "index.html":
            require_contains(html, "Translations", relative_path)
            require_contains(html, "/styles.css?v=home2", relative_path)
            require_contains(html, "/app.js?v=home7", relative_path)
        if relative_path in {"templates/reading.html", "templates/source.html"}:
            require_contains(html, "/assets/static-reader.css?v=static2", relative_path)
            require_contains(html, "Path</summary>", relative_path)


def check_page_frame_css(relative_path: str, css: str) -> None:
    for needle in [
        ".page {",
        "max-width: var(--page-frame-width",
        "background-color: var(--page-frame-background",
        "border: 1px solid var(--page-frame-border",
        "box-shadow: var(--page-frame-shadow",
    ]:
        require_contains(css, needle, relative_path)


def check_reader_css(relative_path: str, css: str) -> None:
    common_needles = [
        ".reader {",
        "background: var(--reader-background",
        "border: 1px solid var(--reader-border",
        "@media (max-width: 860px)",
        "width: auto;",
        "margin: 0 10px 24px;",
    ]
    for needle in common_needles:
        require_contains(css, needle, relative_path)
    if relative_path == "assets/reader-work.css":
        require_contains(css, "width: calc(100% - 64px);", relative_path)
        require_contains(css, "grid-template-columns: minmax(0, 1fr) 340px;", relative_path)
    elif relative_path == "assets/static-reader.css":
        for needle in [
            ".source-links",
            ".source-details",
            ".source-details summary",
            ".source-details[open] summary::after",
        ]:
            require_contains(css, needle, relative_path)
    else:
        require_contains(css, "width: var(--reader-column-width", relative_path)


def check_home_css() -> None:
    relative_path = "styles.css"
    css = read_site_file(relative_path)
    check_page_frame_css(relative_path, css)
    for needle in [
        ".nav-column {",
        "flex: 0 0 var(--reader-column-width",
        "background: var(--reader-background",
        "border: 1px solid var(--reader-border",
        ".reading-path-link.primary",
        ".reading-path-links",
        ".recent-work",
        ".recent-work-meta",
        "@media (max-width: 860px)",
    ]:
        require_contains(css, needle, relative_path)

    responsive = css.split("@media (max-width: 860px)", maxsplit=1)[1]
    for needle in [
        ".nav-column {",
        "flex: 0 1 auto;",
        "width: 100%;",
        "padding: 0 10px 24px;",
    ]:
        require_contains(responsive, needle, f"{relative_path} responsive block")


def check_home_script() -> None:
    script = read_site_file("app.js")
    for needle in [
        "START_READING_LIMIT",
        "RECENT_WORK_STORAGE_KEY",
        "START_READING_WORK_IDS",
        "START_READING_LABELS",
        "ROOT_LINK_LABELS",
        "CATEGORY_SUBTITLES",
        'nietzsche: ["M", "FW", "Za-I", "JGB", "GM", "GD"]',
        '"oshb.Gen", "oshb.Ps", "oshb.Isa", "sblgnt.Matt", "sblgnt.John", "sblgnt.Rom"',
        'kierkegaard: ["ee1", "ee2", "fb", "g", "ba", "ps"]',
        '"Group_Notebooks"',
        "Morgenröthe / 아침놀",
        "Big Typescript",
        "Philosophical Investigations",
        "function corpusLinks",
        "function uniqueLinks",
        "function startReadingLabel",
        "function startReadingTitle",
        "function rootLinkLabel",
        "function categorySubtitle",
        "function storedRecentWork",
        "function recentWorkMarkup",
        "Continue reading",
        "linksByWorkId",
        "START_READING_WORK_IDS[corpus.id]",
        "START_READING_LIMIT",
    ]:
        require_contains(script, needle, "app.js")


def check_reader_pages_css() -> None:
    for relative_path in READER_CSS_FILES:
        css = read_site_file(relative_path)
        check_page_frame_css(relative_path, css)
        check_reader_css(relative_path, css)


def check_study_target_ui() -> None:
    script = read_site_file("assets/study.js")
    for needle in [
        "function noteManageHref",
        "Target URL missing",
        ">Edit</a>",
    ]:
        require_contains(script, needle, "assets/study.js")

    css = read_site_file("assets/study.css")
    for needle in [
        "overflow-wrap: anywhere;",
        ".note-footer",
        ".note-footer .note-meta",
        ".note-actions",
    ]:
        require_contains(css, needle, "assets/study.css")


def check_search_ui() -> None:
    html = read_site_file("search.html")
    script = read_site_file("assets/search.js")
    css = read_site_file("assets/search.css")
    for needle in [
        "/assets/search.css?v=phase19",
        "/assets/search.js?v=phase28",
        'href="/translations"',
        "Translations",
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'id="searchSubmit"',
        'id="searchClear"',
        'id="searchActiveFilters"',
        'class="form-actions"',
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "search.html")
    for needle in [
        "activeSearchController",
        "activeSearchRequest",
        "setSearchBusy",
        "renderSearchPending",
        "function renderEmptySearch",
        "function renderSearchStart",
        "search-start-links",
        "Search the archive.",
        "No matching passages.",
        "const bodyMarkup = body ?",
        "function clearSearchFilters",
        "function updateSearchClearState",
        "function updateSearchFilterSummary",
        "function removeSearchFilter",
        "function resultGroupHeader",
        "function resultKind",
        "function resultSnippet",
        "function resultSummaryNav",
        "function compactCount",
        "function searchStatusText",
        "function cleanText",
        "function corpusLabel",
        "function reviewStateLabel",
        "function resultMeta",
        "function resultFooter",
        "result-actions-inline",
        'aria-label="Result actions"',
        "search-results-works",
        "search-results-segments",
        "Passage",
        "Passages",
        "search-results-notes",
        "result-group-count",
        "result-kind",
        "searchClear.addEventListener",
        "activeFiltersEl.addEventListener",
        "filter-chip",
        "data-empty-action=\"clear-search\"",
        "search-skeleton",
        "activeSearchController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
        "Could not complete search.",
    ]:
        require_contains(script, needle, "assets/search.js")
    for noisy_action in [
        "Open work",
        "Open source",
        "Open target",
        "Manage note",
    ]:
        require(noisy_action not in script, f"assets/search.js should not expose redundant search action {noisy_action!r}")
    for needle in [
        ".search-form.is-searching",
        ".spacer",
        "height: 136px",
        ".reader-header",
        "margin-bottom: 16px",
        "padding-bottom: 10px",
        ".form-actions",
        ".secondary-action",
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".active-filters",
        ".active-filters.has-filters",
        ".filter-chip",
        ".result-summary-nav",
        ".result-summary-link",
        ".result-group-header",
        ".result-group-count",
        ".result-kind",
        ".result-kind.work",
        ".result-kind.segment",
        ".result-kind.note",
        ".result-title > a",
        ".result-footer",
        ".result-actions-inline",
        ".snippet-link",
        "grid-template-columns: minmax(0, 1fr) auto",
        "justify-content: flex-end",
        ".search-form.is-searching #searchSubmit",
        "padding-bottom: 12px",
        ".empty-state",
        ".search-start",
        ".search-start-links",
        ".empty-actions",
        ".empty-actions a",
        ".search-skeleton-line",
        "@keyframes archive-spin",
        "@keyframes archive-skeleton",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/search.css")


def check_notes_ui() -> None:
    html = read_site_file("notes.html")
    script = read_site_file("assets/notes.js")
    css = read_site_file("assets/notes.css")
    for needle in [
        "/assets/notes.css?v=notes19",
        "/assets/notes.js?v=notes28",
        'id="notesSubmit"',
        'id="notesClear"',
        'id="notesActiveFilters"',
        'id="notesExportTools"',
        "Export</summary>",
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'class="export-tools"',
        'class="export-row"',
        'class="form-actions"',
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "notes.html")
    for needle in [
        "activeNotesController",
        "activeNotesRequest",
        "setNotesBusy",
        "notesExportTools",
        "exportTools.hidden = notes.length === 0",
        "setActionButtonBusy",
        "renderNotesPending",
        "function notesSummaryCounts",
        "function notesSummaryButton",
        "function renderNotesSummary",
        "function archiveCorpusById",
        "function corpusDisplayName",
        "function workDisplayName",
        "function noteTitle",
        "function noteContext",
        'statusEl.textContent = "";',
        "function renderNoteFooter",
        "note-footer",
        "note-danger-actions",
        "Delete</summary>",
        "Confirm</button>",
        "data-notes-summary-filter",
        "recentlyChangedNoteId",
        "function revealRecentlyChangedNote",
        "Recently changed note",
        "Recently changed note is hidden by the current filters.",
        "recentNote.scrollIntoView",
        "recentNote.focus({ preventScroll: true })",
        "function prefersReducedMotion",
        "function focusNoteEditor",
        "function resetNoteEditor",
        "noteField.setSelectionRange",
        "Edit cancelled.",
        "editForm.requestSubmit",
        "function renderEmptyNotes",
        "function updateNotesListChrome",
        "form.hidden = !showTools",
        "No notes yet.",
        "Find work",
        "Study",
        "function clearNotesFilters",
        "queryInput.focus();",
        "function updateNotesClearState",
        "function updateNotesFilterSummary",
        "activeFiltersEl.hidden = chips.length === 0",
        "function removeNotesFilter",
        "notesClear.addEventListener",
        "activeFiltersEl.addEventListener",
        "filter-chip",
        "data-empty-action=\"clear-filters\"",
        "notes-skeleton",
        "archiveCorpora = payload.corpora || []",
        "activeNotesController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
    ]:
        require_contains(script, needle, "assets/notes.js")
    for noisy_action in [
        "Open target",
        "Open work",
        "Manage note",
        "Edit note",
    ]:
        require(noisy_action not in script, f"assets/notes.js should keep Notes actions concise without {noisy_action!r}")
    for needle in [
        ".notes-form.is-loading",
        ".notes-form[hidden]",
        ".translations-form[hidden]",
        ".active-filters[hidden]",
        ".spacer",
        "height: 136px",
        ".reader-header",
        "margin-bottom: 16px",
        "padding-bottom: 10px",
        ".form-actions",
        ".secondary-action",
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".export-tools",
        ".export-tools summary",
        ".export-tools[open] summary::after",
        ".active-filters",
        ".active-filters.has-filters",
        ".filter-chip",
        ".notes-summary-nav",
        ".notes-summary-filter",
        ".note-card.is-recent",
        ".note-card.is-recent:focus",
        ".note-card.is-editing",
        ".note-title > a",
        ".note-context",
        ".note-footer",
        ".note-footer .note-meta",
        ".note-actions a",
        ".note-danger-actions",
        ".note-danger-actions summary",
        ".note-danger-actions summary::after",
        ".note-danger-actions[open] summary::after",
        ".note-danger-actions button",
        ".note-edit-actions",
        "grid-template-columns: repeat(2, minmax(0, 1fr))",
        "justify-content: flex-end",
        "@keyframes archive-note-highlight",
        ".notes-form.is-loading #notesSubmit",
        "padding-bottom: 12px",
        ".empty-state",
        ".empty-actions",
        ".empty-actions a",
        ".notes-skeleton-line",
        ".note-actions button.is-working",
        "@keyframes archive-spin",
        "@keyframes archive-skeleton",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/notes.css")


def check_translations_ui() -> None:
    html = read_site_file("translations.html")
    script = read_site_file("assets/translations.js")
    base_css = read_site_file("assets/notes.css")
    css = read_site_file("assets/translations.css")
    for needle in [
        "/assets/notes.css?v=notes19",
        "/assets/translations.css?v=trans23",
        "/assets/translations.js?v=trans53",
        '<option value="">All corpora</option>',
        'id="translationsListTools"',
        "Filter</summary>",
        'id="translationsSubmit"',
        'id="translationsClear"',
        'id="translationsReviewQueue"',
        'id="translationsExportTools"',
        'id="translationsExportTools" class="export-tools" hidden',
        "aria-keyshortcuts=\"Q\"",
        'id="translationsWorkOptions"',
        'id="translationsActiveFilters"',
        'id="translationsExportMarkdown"',
        'id="translationsExportJson"',
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'class="review-export-row"',
        'class="export-tools"',
        "Export</summary>",
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "translations.html")
    for needle in [
        "activeController",
        "activeRequest",
        "archiveCorpora",
        "pendingReviewQueueFocus",
        "pendingReviewQueueMessage",
        "translationsExportTools",
        "translationsListTools",
        "function hasSearchFilters",
        "listTools.open = shouldOpenTools",
        "exportTools.hidden = visible.length === 0",
        "if (!visible.length) exportTools.open = false",
        "setBusy",
        "function prefersReducedMotion",
        "renderPending",
        "function selectedCorpusArchive",
        "function archiveCorpusById",
        "function corpusDisplayName",
        "function compactWorkMeta",
        "function workDisplayName",
        "function sentenceDisplayName",
        "const bibleMatch",
        "function archiveWorkOptions",
        "function updateWorkOptions",
        "function renderEmptyRecords",
        "function updateTranslationsListChrome",
        "form.hidden = !showTools",
        "No translations yet.",
        "const bodyMarkup = body ?",
        "Find work",
        "Study",
        "function clearFilters",
        "queryInput.focus();",
        "function updateFilterSummary",
        "activeFiltersEl.hidden = chips.length === 0",
        "function removeFilter",
        "function renderSummary",
        "counts.total <= 0",
        "function visibleSummaryStates",
        "Translation status overview",
        "function reviewActionsVisible",
        'statusEl.textContent = "";',
        "function renderRecord",
        "function recordContext",
        "function recordGroupKey",
        "function groupedTranslationRecords",
        "reviewedCount",
        "function groupWorkUrl",
        "function groupSavedExportUrl",
        "function renderGroupActions",
        "translation-record-group-actions",
        ">Read</a>",
        ">Saved</a>",
        "function renderRecordGroups",
        "showContext",
        "data-translation-record-group",
        "translation-record-group-title",
        "function visibleReviewStates",
        "showReviewBadge",
        "showReviewActions",
        "record.target_label || sentenceDisplayName(record)",
        "corpusDisplayName(record.corpus_id)",
        "workDisplayName(record.corpus_id, record.work_id)",
        "translation-record-heading",
        "translation-record-kicker",
        "translation-record-context",
        "Review status:",
        "review-badge",
        "translation-record-title",
        "translation-record-footer",
        "aria-label=\"Commentary\"",
        "<h3>Commentary</h3>",
        "Original</summary>",
        "function generatedRecords",
        "function updateReviewQueueButton",
        "reviewQueueButton.hidden = generatedCount === 0",
        "Review translations",
        "function focusFirstReviewQueueRecord",
        "function clearReviewTargetHighlight",
        "function openReviewTargetSource",
        "source.open = true",
        "function openReviewQueue",
        "function visibleRecordCards",
        "function focusedRecordCard",
        "function focusRecordCard",
        "function navigateRecordFocus",
        "function triggerFocusedReviewAction",
        "function openFocusedSource",
        "function isTypingTarget",
        'event.key === "ArrowDown"',
        "aria-keyshortcuts=\"R\"",
        "aria-keyshortcuts=\"X\"",
        "aria-keyshortcuts=\"O\"",
        "data-open-source",
        "To check",
        "Nothing to check.",
        "Saved.",
        "Next item.",
        "function updateRecordReview",
        "function reviewActionMessage",
        "Rejected.",
        "Moved to check.",
        "const actionMessage = reviewActionMessage(nextState)",
        "translation-record-summary-tools",
        "translation-record-summary-tools translation-record-summary",
        "data-translation-summary-filter",
        "review_state: reviewState",
        "/api/sentence-translations/export",
        "/api/sentence-translations/",
        "Could not save.",
        "translationsExportMarkdown",
        "translationsExportJson",
        'params.set("q", query)',
        "primary-review-action",
        "translation-more-actions",
        "<summary>Reject</summary>",
        "Confirm reject",
        'title="Source"',
        "reviewActionsVisible() && visibleReviewStates(visible).size > 1",
    ]:
        require_contains(script, needle, "assets/translations.js")
    require_ordered_markers(
        js_function_body(script, "renderRecord"),
        [
            "translation-record-heading",
            "translation-record-title",
            "translation-text",
            "translation-commentary",
            "Original</summary>",
            "translation-record-footer",
            "translation-actions",
        ],
        "renderRecord review-first translation card layout",
    )
    for needle in [
        ".translations-form",
        ".list-tools",
        ".list-tools[hidden]",
        ".list-tools summary",
        ".list-tools summary::after",
        ".list-tools[open] summary::after",
        ".list-tools .translations-form",
        ".list-tools .export-tools",
        ".translation-record-summary-tools",
        ".translation-record-summary",
        "background: transparent",
        ".translation-review-queue",
        ".translation-review-queue:not(:disabled)",
        ".translation-record-card",
        ".translation-record-group",
        ".translation-record-group-title",
        ".translation-record-group-title strong",
        ".translation-record-group-actions",
        ".translation-record-group-actions a",
        ".translation-record-group .translation-record-card:first-of-type",
        ".translation-record-card:focus",
        ".translation-record-card.is-review-target",
        ".translation-record-card.is-review-target:focus",
        "border-left: 3px solid #b00000",
        ".translation-record-card[data-review-state=\"generated\"]",
        ".translation-record-heading",
        "grid-template-columns: minmax(0, 1fr) auto",
        ".translation-record-kicker",
        "justify-self: end",
        ".translation-record-context",
        ".translation-record-kicker .review-badge",
        ".translation-record-title",
        "-webkit-line-clamp: 2",
        ".translation-record-title a",
        ".translation-record-footer",
        ".translation-source",
        ".translation-source summary",
        ".translation-source blockquote",
        ".translation-text",
        ".translation-commentary",
        ".translation-commentary h3",
        "clip: rect(0, 0, 0, 0)",
        ".translation-actions",
        ".translation-more-actions",
        ".translation-more-actions summary",
        ".translation-more-actions summary::after",
        ".translation-more-actions[open] summary::after",
        ".translation-more-actions button",
        "@media (hover: hover) and (pointer: fine)",
        ".translation-record-card:hover .translation-more-actions",
        ".translation-record-card:focus .translation-more-actions",
        ".translation-record-card:focus-within .translation-more-actions",
        ".translation-record-card.is-review-target .translation-more-actions",
        ".translation-actions .primary-review-action:not(:disabled)",
        ".translation-actions button.is-working",
        "@media (prefers-reduced-motion: reduce)",
        "@media (max-width: 860px)",
        "overflow-x: auto",
        "scrollbar-width: thin",
        "max-height: 6.4em",
        "display: block;",
        "justify-content: center",
    ]:
        require_contains(css, needle, "assets/translations.css")
    for needle in [
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".export-tools",
        ".export-tools summary",
        ".review-export-row",
    ]:
        require_contains(base_css, needle, "assets/notes.css")


def check_study_ui() -> None:
    html = read_site_file("study.html")
    script = read_site_file("assets/study.js")
    css = read_site_file("assets/study.css")
    for needle in [
        "/assets/study.css?v=study20",
        "/assets/study.js?v=study31",
        'id="studySubmit"',
        'id="studyClear"',
        'id="studyActiveFilters"',
        'id="studyOverview"',
        'class="study-overview"',
        'aria-label="Study overview"',
        'id="studyExportTools"',
        'id="studyExportMarkdown"',
        'id="studyExportTranslations"',
        "Saved translations</a>",
        'aria-label="Export study material"',
        "Export</summary>",
        'class="filter-panel"',
        'class="filter-panel-fields"',
        'class="export-tools"',
        'class="export-row"',
        'class="form-actions"',
        'role="status"',
        'aria-busy="false"',
    ]:
        require_contains(html, needle, "study.html")
    for needle in [
        "activeStudyController",
        "activeStudyRequest",
        "setStudyBusy",
        "studyExportTools",
        "studyExportTranslations",
        "function translationExportParams",
        "/api/sentence-translations/export",
        "reviewedTranslationCount",
        "exportTools.hidden = count === 0 && reviewedTranslationCount === 0",
        "exportTranslations.hidden = reviewedTranslationCount === 0",
        "studyOverview",
        "function translationSummaryParams",
        "/api/sentence-translations/summary",
        "function translationStatusLink",
        "function renderStudyOverview",
        "const notesMarkup = notesLabel",
        "Review translations",
        "Translation study status",
        "Saved translations",
        "renderStudy(payload, translationSummary)",
        "renderStudyPending",
        "function renderEmptyStudy",
        "function updateStudyListChrome",
        "form.hidden = !showTools",
        "function renderNoteFooter",
        "function archiveCorpusById",
        "function corpusDisplayName",
        "function workDisplayName",
        ">Read</a>",
        ">Notes</a>",
        "function studyCountLabel",
        "function studyGroupMeta",
        "archiveCorpora = payload.corpora || []",
        'statusEl.textContent = "";',
        "Notes",
        "Find work",
        "function clearStudyFilters",
        "queryInput.focus();",
        "function updateStudyClearState",
        "function updateStudyFilterSummary",
        "activeFiltersEl.hidden = chips.length === 0",
        "function removeStudyFilter",
        "studyClear.addEventListener",
        "activeFiltersEl.addEventListener",
        "filter-chip",
        "data-empty-action=\"clear-filters\"",
        "study-skeleton",
        "activeStudyController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
    ]:
        require_contains(script, needle, "assets/study.js")
    for noisy_action in [
        "Open work",
        "Edit notes",
        "Open target",
        "Edit note",
        "study-note-more-actions",
    ]:
        require(noisy_action not in script, f"assets/study.js should keep Study actions concise without {noisy_action!r}")
    for needle in [
        ".study-form.is-loading",
        ".study-form[hidden]",
        ".active-filters[hidden]",
        ".spacer",
        "height: 136px",
        ".reader-header",
        "margin-bottom: 16px",
        "padding-bottom: 10px",
        ".form-actions",
        ".secondary-action",
        ".filter-panel",
        ".filter-panel summary",
        ".filter-panel-fields",
        ".export-tools",
        ".export-tools summary",
        ".export-tools[open] summary::after",
        ".active-filters",
        ".active-filters.has-filters",
        ".study-overview",
        ".study-overview[hidden]",
        ".study-overview-notes",
        ".study-overview-translations",
        ".study-overview-translations a",
        ".study-overview-translations strong",
        ".filter-chip",
        ".study-form.is-loading #studySubmit",
        "padding-bottom: 12px",
        ".group-meta",
        ".study-group-context",
        ".study-tags-panel",
        ".study-tags-panel summary",
        ".study-tags-panel[open] summary::after",
        ".study-tags",
        ".study-note + .study-note",
        ".note-title > a",
        ".note-footer",
        ".note-footer .note-meta",
        ".empty-state",
        ".empty-actions",
        ".empty-actions a",
        ".study-skeleton-line",
        "@keyframes archive-spin",
        "@keyframes archive-skeleton",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/study.css")


def check_work_source_bundle_ui() -> None:
    template = read_site_file("templates/work.html")
    for needle in [
        'id="copySourceBundle"',
        "citation-copy-options",
        "citation-copy-actions",
        'id="copyCitation" aria-label="Copy citation"',
        'class="citation-copy-options" aria-label="Copy options"',
        "Copy</summary>",
        'id="copyUrl" aria-label="Copy URL"',
        'id="copySourceBundle" aria-label="Copy source bundle"',
        ">Source bundle</button>",
    ]:
        require_contains(template, needle, "templates/work.html")

    script = read_site_file("assets/reader-work.js")
    for needle in [
        "function sourceBundleUrl",
        "function citationPreviewText",
        "function updateCitationPreview",
        "citationPreview.title = \"Copy includes source URL.\"",
        "Source URL included when copied.",
        "await copyText(citationText())",
        "function targetSnapshot",
        "function selectedSentenceTargetSnapshot",
        "function noteTargetForSave",
        "function updateNoteTargetPreview",
        "function lockCurrentNoteTarget",
        "function unlockNoteTarget",
        "function syncTargetDependentViews",
        'new Set(["segment", "section", "paragraph", "verse"])',
        "/api/source-target",
        "/api/sentence-translation",
        "requestSentenceTranslation(false)",
        "Source bundle requires a section, paragraph, or verse target.",
        "Source bundle URL copied.",
        "navigateSentence(1)",
        "updateTranslationReview(\"reviewed\", quickAction)",
        "setTranslationMode(\"reading\")",
        "gemmaRuntimeStatus",
        "gemmaRuntimeStatusText",
        "gemmaRuntimeCheckButton",
        "function setGemmaRuntimeIndicator",
        "async function checkGemmaRuntimeStatus",
        "/api/health",
        "setGemmaRuntimeIndicator(\"checking\", \"Checking translator\",",
        "Translator ready",
        "Translator offline",
        "Translator unavailable",
        "gemmaRuntimeCheckButton.addEventListener",
        "translationRecordsSummary",
        "function setTranslationRecordsSummary",
        "translation-records-summary-main",
        "translationRecordsSummary.title = detailLabel",
        "needs-review",
        "function updateTranslationExportLinks",
        "translationSentenceStates",
        "TRANSLATION_STATE_LABELS",
        "TRANSLATION_STATE_SHORT",
        "nextUnstudiedSentenceButton",
        "nextReviewSentenceButton",
        "continueStudyButton",
        "studyProgressText",
        "function setStudyProgress",
        "function updateStudyProgress",
        "function translationStateCountsFromSentences",
        "translationSentenceStatesLoaded",
        "function sentenceHasTranslationState",
        "function sentenceTranslationState",
        "function nextUnstudiedSentenceIndex",
        "function firstUnstudiedSentenceIndex",
        "function continueStudySentenceIndex",
        "function nextGeneratedSentenceIndex",
        "function navigateToNextUnstudiedSentence",
        "function navigateToNextReviewSentence",
        "function continueStudy",
        "Next to check",
        "review-generated",
        "wantsPreview",
        "Preview session",
        "preview-session",
        "function renderStudySessionPreviewPending",
        "function sessionPreviewItems",
        "function sessionPreviewTargetId",
        "function openSessionPreviewTarget",
        "data-session-preview-target",
        "data-session-preview-toggle",
        "function toggleSessionPreviewGroup",
        "data-session-preview-copy",
        "async function copyStudySessionMarkdown",
        "Copy pack",
        "Study pack copied.",
        "Show less",
        "Show all ${group.querySelectorAll(\"li\").length}",
        "function renderStudySessionPreview",
        "function renderStudySessionPreviewError",
        "async function previewStudySession",
        "Study session preview ready.",
        "Study session preview unavailable",
        "Open pack",
        "to check",
        "All sentences have translations.",
        "No unstudied sentence after current position.",
        "TRANSLATION_REVIEW_CHIP_LABELS",
        "TRANSLATION_REVIEW_CHIP_HINTS",
        "Translation to check",
        "const reviewLabel = stateHint || stateLabel",
        "<span>Source</span>",
        "aria-label=\"${escapeHtml(reviewLabel)}\"",
        "function applySentenceTranslationState",
        "function applySentenceTranslationStates",
        "function clearSentenceTranslationStates",
        "data-translation-state-short",
        "data-translation-state-label",
        "sentence_state_count",
        "async function loadTranslationRecordsSummary",
        "/api/sentence-translations/summary",
        "Translations",
        "review_state_counts",
        "function setTranslationReviewVisualState",
        "function flashTranslationReviewState",
        "function flashSentenceReviewState",
        "translationReviewFlashTimer",
        "sentenceReviewFlashTimer",
        "exportAllTranslations",
        "exportStudySession",
        "/api/study-session/export",
        "notes_review_state",
        "translation_review_state",
        "studySessionSummary",
        "function setStudySessionSummary",
        "function studySessionExportUrl",
        "function loadStudySessionSummary",
        "await loadStudySessionSummary();",
        "Study pack:",
        "review_state\", \"all\"",
        "renderTranslationPending",
        "translation-pending-context",
        "translation-pending-commentary",
        "Commentary will appear with the translation.",
        "selectedSentencePositionLabel()",
        "renderTranslationError",
        "GEMMA_RUNTIME_COMMAND",
        "function translationErrorIsRuntime",
        "function runtimeRecoveryMarkup",
        "translation-runtime-hint",
        "Translator is offline.",
        "Start the translator, then retry this sentence.",
        "translation-runtime-details",
        "Startup command",
        "translation-runtime-command",
        "translation-runtime-command-row",
        "data-translation-copy-runtime",
        "data-translation-check-runtime",
        "Check translator",
        "Copy startup command",
        "Start command copied.",
        ".\\\\run_reader_with_gemma.ps1",
        "translation-error-actions",
        "translation-unavailable-copy",
        "translation-recovery-panel",
        "renderTranslationCancelled",
        "Translation cancelled.",
        "cancelTranslationRequest",
        "data-translation-cancel",
        "data-translation-retry",
        "data-translation-retry=\"${escapeHtml(retryMode)}\"",
        "Regenerate again",
        "retry.dataset.translationRetry === \"regenerate\"",
        "Translation request cancelled.",
        "No translation was saved",
        "resetTranslationOutputScroll",
        "translationOutput.scrollTop = 0",
        "setActionButtonBusy",
        "translation-pending-result",
        "translation-pending-copy",
        "Preparing translation",
        "Refreshing study card",
        "Could not save note.",
        "renderCommentary",
        "renderTranslationEmptyState",
        "translation-empty-state",
        "translation-empty-copy",
        "Click a sentence to read translation and commentary.",
        "syncTranslationModeDensity",
        "translationJumpNav",
        "translationResultToolbar",
        "translation-result-toolbar",
        "translation-result-toolbar translation-result-details translation-extra",
        "<span>Source</span>",
        "translation-result-kicker\">Sentence",
        "<h3>Original</h3>",
        "translation-result-meta",
        "translation-result-target",
        "translationOutputUsesInternalScroll",
        "scrollTranslationSectionIntoView",
        "const stickyOffset = 8",
        "data-translation-jump",
        "data-translation-section=\"translation\"",
        "data-translation-section=\"commentary\"",
        "translation-result",
        "translation-section-primary",
        "recentlyChangedNoteId",
        "Note saved and highlighted.",
        "setStudyPanelExpanded",
        "updateStudyPanelScrim",
        "studyPanelScrim",
        "beginStudyPanelDrag",
        "updateStudyPanelDrag",
        "finishStudyPanelDrag",
        "cancelStudyPanelDrag",
        "STUDY_PANEL_DRAG_THRESHOLD",
        "ignoreNextStudyPanelToggleClick",
        "pointerdown",
        "pointermove",
        "pointerup",
        "pointercancel",
        'event.key === "Escape"',
        "selectedSentencePositionLabel",
        "rememberRecentWork",
        "RECENT_WORK_STORAGE_KEY",
        "sentencePositionText",
        "function selectSentenceFromHash",
        "setStudyPanelExpanded(true)",
        "studyPanelToggleSummary",
        "updateStudyPanelToggleLabel",
        "Select sentence",
        "translating",
        "needs retry",
        "const action = expanded ? \"Back to text\" : \"Study\"",
        "prefersReducedMotion",
        "sentenceScrollBlock",
        "activeTranslationController",
        "activeTranslationTargetKey",
        "pendingTranslationRegenerate",
        "selectedTranslationTargetKey",
        "Translation is already running...",
        "activeTranslationController.abort()",
        "signal: controller.signal",
        'error.name === "AbortError"',
        "ACTION_CONFIRM_MS",
        "pendingActionConfirmation",
        "actionConfirmationConfig",
        "armActionConfirmation",
        "handleConfirmedAction",
        'handleConfirmedAction("regenerate")',
        "Confirm regenerate",
        "Click Confirm regenerate to replace this translation.",
        "requestSentenceTranslation(true)",
        'handleConfirmedAction("reject")',
        "Confirm reject",
        "Click Confirm reject to exclude this cached translation.",
        "hasPendingActionConfirmation",
        "clearActionConfirmations",
        "Pending action cancelled.",
        "Pending action expired.",
        "setTranslationStatus(config.status, true)",
        "isMobileStudyLayout",
        "function visibleViewportTop",
        "function visibleViewportHeight",
        "function visibleViewportBottom",
        "studyPanelViewportHeight",
        "mobileSentenceSafeBottom",
        "adjustSentenceAboveStudyPanel",
        "keepSentenceAboveStudyPanel",
        "function handleViewportLayoutChange",
        "window.visualViewport.addEventListener",
        "window.scrollBy",
        "window.setTimeout(() => adjustSentenceAboveStudyPanel(node)",
        "behavior: prefersReducedMotion() ? \"auto\" : \"smooth\"",
        "STUDY_PANEL_STORAGE_KEY",
        "storedStudyPanelExpanded",
        "rememberStudyPanelExpanded",
        "updateSentenceContext",
        "sentence-context-item",
        "readingPosition",
        "initializeReadingPositionTracker",
        "IntersectionObserver",
        "visibleSentenceNodes",
        "requestAnimationFrame(refreshReadingPosition)",
        "readingCueTargetLine",
        "updateReadingPosition(node)",
        "reading-position-main",
        "reading-position-excerpt",
        "is-selectable-cue",
        "Current reading position: ${label}. ${excerpt}",
        "function studyReadingCueSentence",
        "data-reading-cue-select",
        "readingPosition.addEventListener",
        "function renderTranslationTarget",
        "function selectedSentenceIsVisible",
        "function updateTranslationTargetViewState",
        "translationTarget.dataset.sourceState",
        "status.dataset.sourceState",
        "jumpButton.classList.toggle(\"is-source-away\"",
        "function focusSelectedSourceSentence",
        "function flashSourceFocus",
        'event.key.toLowerCase() === "s"',
        "translation-target-excerpt",
        "data-selected-source-jump",
        'aria-keyshortcuts="S"',
        "Source off screen",
        "NOTE_DRAFT_STORAGE_KEY",
        "noteDraftPayload",
        "readerSessionStorage",
        "saveNoteDraft",
        "locked_target",
        "restoreNoteDraft",
        "clearNoteDraft",
        "sessionStorage",
        "Note draft restored.",
        "Note target locked.",
        "Note target follows selection.",
        "const target = noteTargetForSave()",
        "noteSort",
        "noteFilterClear",
        "function updateNoteFilterClearState",
        "function clearNoteFilter",
        "Note filter cleared.",
        "function normalizedNoteReviewState",
        "function noteReviewLabel",
        "function noteReviewAction",
        "function noteReviewActionLabel",
        "noteListSummary",
        "function sortedNotes",
        "function renderNotesPending",
        "function noteListSummaryText",
        "function renderNotesUnavailable",
        "function syncNotesFilterToolsVisibility",
        "notesFilterTools.hidden = !showTools",
        "function renderNotesList",
        "function revealRecentNote",
        "Recently changed note",
        "Recently changed note is hidden by the current filter. Use Clear filter to show it.",
        "recentNote.focus({ preventScroll: true })",
        "No notes match this filter.",
        "data-notes-empty-action=\"clear-filter\"",
        "function noteTargetHref",
        ">Source</a>",
        "note-danger-actions",
        "<summary>Delete</summary>",
        "delete-note",
        "Save",
        "Reopen",
        "mark-reviewed-note",
        "mark-raw-note",
        "notes-list-skeleton",
        "No notes yet.",
        "Notes unavailable.",
        "function syncConceptsPanelAvailability",
        "conceptsTab.hidden = true",
        'conceptsTab.classList.remove("active")',
        "function visibleStudyTabs",
        "copyStudyCard",
        "function translationNoteDraftText",
        "function focusNoteComposer",
        "function noteAlreadyIncludesDraft",
        "function updateNoteReview",
        "Already in this note.",
        "Already in Notes.",
        "noteForm.scrollIntoView",
        "preventScroll: isMobileStudyLayout()",
        "Ready to save.",
        "Ready to save in Notes.",
        "Added to this note. Review and save.",
        "Added to Notes.",
        "noteText.setSelectionRange",
        "translationStudyCardText",
        "function translationQuickActions",
        "function focusNextSentenceAction",
        "nextAction.focus({ preventScroll: true })",
        "translation-reading-actions",
        "data-translation-quick-action=\"next-sentence\"",
        "Select and translate next sentence",
        "Save translation",
        "Add note from translation",
        "Next sentence",
        "translation-quick-actions translation-extra",
        "data-translation-quick-action",
        "Continue study",
        "Save",
        "Add note",
        "Selected source",
        "Clipboard copy failed",
        "function revealFreshTranslationResult",
        "has-fresh-result",
        "just-studied",
        'target?.closest?.(".study-page")',
        "activateStudyTabByIndex",
        "ensureActiveStudyTabVisible",
        "scrollIntoView({",
        "inline: \"nearest\"",
        "studyPage.scrollTop = 0",
        "function studyPanelStickyOffset",
        "studyPage.scrollTo({ top, behavior })",
        "section.scrollIntoView({ block: \"start\", inline: \"nearest\", behavior })",
        "aria-selected",
        "panel.hidden = !active",
        'event.key === "ArrowRight"',
        'event.key === "Home"',
    ]:
        require_contains(script, needle, "assets/reader-work.js")
    require_ordered_markers(
        js_function_body(script, "updateCitationPreview"),
        [
            "citationPreviewText()",
            "citationPreview.textContent = preview",
            "Copy includes source URL.",
        ],
        "updateCitationPreview screen preview stays shorter than copied citation",
    )
    require_ordered_markers(
        js_function_body(script, "renderTranslationEmptyState"),
        [
            '<section class="translation-section translation-section-primary"',
            'data-translation-section="translation"',
            "translation-empty-copy",
        ],
        "renderTranslationEmptyState quiet empty layout",
    )
    for function_name, commentary_marker, trailing_marker in [
        ("renderTranslationPending", '<section class="translation-section translation-commentary translation-pending-commentary"', "translation-loading-actions"),
        ("renderTranslationError", '<section class="translation-section translation-commentary"', "translation-recovery-panel"),
        ("renderTranslationCancelled", '<section class="translation-section translation-commentary"', "translation-recovery-panel"),
        (
            "renderTranslationRecord",
            "${renderCommentary(record.commentary || record.interpretation || \"\")}",
            "${translationResultToolbar(record, cached, reviewState)}",
        ),
    ]:
        markers = [
            '<section class="translation-section translation-section-primary"',
            'data-translation-section="translation"',
            commentary_marker,
        ]
        if "translation-commentary" in commentary_marker:
            markers.append('data-translation-section="commentary"')
        if trailing_marker:
            markers.append(trailing_marker)
        require_ordered_markers(
            js_function_body(script, function_name),
            markers,
            f"{function_name} reading-first translation layout",
        )
    require_contains(template, "/assets/reader-work.js?v=common134", "templates/work.html")
    require_contains(template, "/assets/reader-work.css?v=common108", "templates/work.html")
    for needle in [
        '<div class="meta-line">{{HEADER_META}}</div>',
        "reading-desk",
        "toolbar-more",
        "toolbar-more-links",
        "Workspace</summary>",
        'href="/notes?corpus_id={{CORPUS_ID}}&work_id={{WORK_ID}}">Notes</a>',
        'href="/study?corpus_id={{CORPUS_ID}}&work_id={{WORK_ID}}">Study</a>',
        'href="/translations?corpus_id={{CORPUS_ID}}&work_id={{WORK_ID}}">Translations</a>',
        'href="{{SOURCE_HREF}}">Source</a>',
        "source-page",
        "study-page",
        "studyCompanionPanel",
        "studyPanelToggle",
        "studyPanelScrim",
        "Close study panel",
        "study-panel-toggle-action",
        "study-panel-toggle-summary",
        "gemmaRuntimeStatus",
        "gemmaRuntimeStatusText",
        "gemmaRuntimeCheck",
        "Translator status",
        ">Checking translator</span>",
        "translationRecordsSummary",
        "studyProgress",
        "studyProgressText",
        "continueStudy",
        "Continue study",
        "Saved translations</div>",
        "translation-review-tools",
        "translation-review-tools-body",
        "translation-export-tools",
        "translation-export-links",
        "Export</summary>",
        "exportAllTranslations",
        "All Markdown",
        "exportStudySession",
        "Study pack",
        "studySessionSummary",
        "Study pack</div>",
        "aria-label=\"Study. Select sentence\"",
        'aria-controls="studyCompanionPanel"',
        'aria-labelledby="translationCardTitle"',
        'id="translationCardTitle"',
        'class="visually-hidden"',
        "readingPosition",
        "Current reading position",
        "Reading position",
        "noteTargetPreview",
        "lockNoteTarget",
        "Lock target",
        "Write a note...",
        "Target</summary>",
        "note-target-body",
        'aria-pressed="false"',
        "note-options",
        "Note tags",
        "Tags</summary>",
        'aria-label="Save note"',
        "noteTags",
        "notes-filter-tools",
        "Saved notes and filters",
        "Saved</summary>",
        "notes-list-tools",
        "noteListSummary",
        "noteSort",
        "noteFilterClear",
        "Clear filter",
        "aria-busy=\"false\"",
        'aria-describedby="noteStatus"',
        "sentence-context-tools",
        "Nearby text</summary>",
        "sentenceContext",
        "sentence-more-controls",
        "Next options</summary>",
        "sentence-more-controls-body",
        'role="tablist"',
        'role="tab"',
        'role="tabpanel"',
        "study-tab-secondary",
        'aria-controls="study-panel-translation"',
        'aria-labelledby="study-tab-translation"',
        'aria-selected="true"',
        'tabindex="-1"',
        "aria-label=\"Translation result\"",
        "tabindex=\"0\"",
        "aria-keyshortcuts=\"ArrowUp K\"",
        "aria-keyshortcuts=\"ArrowDown J\"",
        "copyStudyCard",
        "translation-card",
        "translation-utility",
        "Study options",
        "translation-utility-group",
        "translation-utility-group-label",
        "View controls",
        "View",
        "Translation display mode",
        "Sentence controls",
        "Study flow",
        "Save & export",
        "<span>More</span>",
        "study-tabs",
        "previousSentence",
        "nextUnstudiedSentence",
        "Next unstudied",
        "nextReviewSentence",
        "Next to check",
        "markTranslationReviewed",
        'title="Regenerate translation"',
        'aria-label="Reject translation"',
        'aria-label="Copy study card"',
        'aria-label="Add note from translation"',
    ]:
        require_contains(template, needle, "templates/work.html")

    css = read_site_file("assets/reader-work.css")
    mobile_css = css.split("@media (max-width: 860px)", maxsplit=1)[1]
    mobile_page_before = css_rule_block(mobile_css, ".page::before", "assets/reader-work.css mobile block")
    for needle in [
        "width: 100%;",
        "background-size: auto var(--header-portrait-height, 128px);",
    ]:
        require_contains(mobile_page_before, needle, ".page::before mobile overflow guard")

    for needle in [
        ".reading-desk",
        ".toolbar-more",
        ".toolbar-more[open]",
        ".toolbar-more summary",
        ".toolbar-more summary::-webkit-details-marker",
        ".toolbar-more summary::after",
        ".toolbar-more[open] summary::after",
        ".toolbar-more-links",
        ".toolbar-more[open] .toolbar-more-links",
        ".visually-hidden",
        "grid-template-columns: minmax(0, 1fr) 340px",
        "gap: 20px",
        ".source-page",
        "padding-right: 20px",
        ".study-page",
        ".page::before",
        "background-size: auto var(--header-portrait-height, 128px)",
        ".study-panel-scrim",
        ".study-panel-scrim[hidden]",
        "background: rgba(238, 238, 238, 0.42)",
        "position: sticky;",
        "position: fixed;",
        "top: auto;",
        ".reader-sentence.loading",
        ".reader-sentence.has-translation-state::after",
        ".reader-sentence[data-translation-state=\"reviewed\"]",
        ".reader-sentence[data-translation-state=\"reviewed\"]::after",
        "content: \"✓\"",
        ".reader-sentence[data-translation-state=\"rejected\"]::after",
        ".reader-sentence.review-state-changed",
        ".translation-card[data-review-state=\"generated\"]",
        ".translation-card[data-review-state=\"reviewed\"]",
        ".translation-card[data-review-state=\"rejected\"]",
        ".translation-card.reading-mode[data-review-state]",
        ".translation-card.review-state-changed",
        ".translation-utility",
        ".translation-utility summary",
        ".translation-utility summary::-webkit-details-marker",
        ".translation-utility summary::after",
        ".translation-utility[open] summary::after",
        ".translation-utility-body",
        ".translation-utility-group",
        ".translation-utility-group + .translation-utility-group",
        ".translation-utility-group-label",
        ".translation-utility .mode-toggle",
        ".sentence-context-tools",
        ".sentence-context-tools[hidden]",
        ".sentence-more-controls",
        ".sentence-more-controls-body",
        ".sentence-context-tools summary",
        ".sentence-more-controls summary",
        ".sentence-context-tools summary::-webkit-details-marker",
        ".sentence-more-controls summary::-webkit-details-marker",
        ".sentence-context-tools summary::after",
        ".sentence-more-controls summary::after",
        ".sentence-context-tools[open] summary::after",
        ".sentence-more-controls[open] summary::after",
        ".translation-review-tools",
        ".translation-review-tools summary",
        ".translation-review-tools[open] summary::after",
        ".translation-review-tools-body",
        ".translation-review-state[data-review-state=\"generated\"]",
        ".translation-review-state[data-review-state=\"reviewed\"]",
        ".translation-review-state[data-review-state=\"rejected\"]",
        ".sentence-controls",
        "grid-template-columns: repeat(2, minmax(0, 1fr))",
        "#regenerateSentence",
        "grid-column: 1 / -1",
        "#nextUnstudiedSentence",
        "#nextReviewSentence",
        ".study-tabs",
        "grid-template-columns: minmax(0, 1.35fr) minmax(0, 1fr) repeat(2, minmax(58px, 0.78fr))",
        ".study-tab:focus-visible",
        ".study-tab.active::after",
        ".study-tab-secondary",
        ".study-tab-secondary.active",
        ".runtime-status",
        ".runtime-status-dot",
        ".runtime-status-text",
        ".runtime-status[data-runtime-state=\"ready\"]",
        "display: none",
        ".runtime-status[data-runtime-state=\"offline\"]",
        ".translation-records-summary",
        ".translation-records-summary[data-records-state=\"has-records\"]",
        ".translation-records-summary[data-records-state=\"needs-review\"]",
        ".study-progress",
        ".study-progress[data-progress-state=\"active\"]",
        ".study-progress[data-progress-state=\"complete\"]",
        ".study-progress[data-progress-state=\"review\"]",
        ".translation-export-tools",
        ".translation-export-tools summary",
        ".translation-export-tools summary::-webkit-details-marker",
        ".translation-export-tools summary::after",
        ".translation-export-tools[open] summary::after",
        ".translation-export-links",
        ".translation-export-link",
        ".translation-export-link.is-empty",
        ".study-session-summary",
        ".study-session-summary[data-session-state=\"has-content\"]",
        ".sentence-controls button.needs-confirm",
        ".translation-review-actions button.needs-confirm",
        "min-height: 38px",
        "grid-template-columns: minmax(104px, 1.35fr) minmax(80px, 1fr) repeat(2, minmax(68px, 0.78fr))",
        "overscroll-behavior-x: contain",
        "scrollbar-width: thin",
        "@keyframes archive-panel-in",
        ".study-panel.active",
        "animation: archive-panel-in 140ms ease-out both",
        ".translation-output.reading-mode .translation-extra",
        ".translation-target-main",
        ".translation-target-status",
        ".translation-target-status::before",
        ".translation-target-status[data-source-state=\"visible\"]::before",
        ".translation-target-status[data-source-state=\"away\"]",
        ".translation-target-excerpt",
        ".translation-target.is-source-visible",
        ".translation-target.is-source-away",
        ".translation-target button",
        ".translation-target button.is-source-away",
        ".runtime-status button",
        ".translation-review-actions",
        ".translation-review-actions button",
        ".reader-sentence.source-focus",
        "@keyframes archive-source-focus",
        ".translation-result",
        ".translation-empty-state",
        ".translation-empty-state .translation-section-primary",
        ".translation-empty-state .translation-section h3",
        ".translation-output .translation-empty-copy",
        ".translation-reading-actions",
        ".translation-reading-actions button",
        ".translation-reading-actions button[data-translation-quick-action=\"next-sentence\"]:not(:disabled)",
        ".translation-reading-actions .translation-quick-state",
        ".translation-pending-result",
        ".translation-pending-copy",
        ".study-session-preview",
        ".study-session-preview-header",
        ".study-session-preview-actions",
        ".study-session-preview-counts",
        ".session-preview-group",
        ".session-preview-group.is-collapsed .session-preview-extra",
        ".session-preview-list",
        ".session-preview-list button",
        ".session-preview-toggle",
        ".session-preview-empty",
        ".translation-result-toolbar",
        ".translation-result-toolbar summary",
        ".translation-result-toolbar summary::-webkit-details-marker",
        ".translation-result-toolbar summary::after",
        ".translation-result-toolbar[open] summary::after",
        ".translation-result-detail-body",
        ".translation-result-meta",
        ".translation-result-kicker",
        ".translation-result-target",
        ".translation-jump-nav",
        ".translation-section.is-jump-target",
        ".translation-section",
        ".translation-result > .translation-section:first-child",
        ".translation-section h3",
        ".translation-card > .translation-output",
        ".translation-section-primary",
        ".translation-section-primary h3",
        ".translation-output.reading-mode .translation-section-primary h3",
        ".translation-source-detail p",
        ".translation-empty-state .translation-primary",
        "border-left: 3px solid #b00000",
        "max-height: clamp(220px, 42vh, 520px)",
        "line-height: 1.7",
        "line-height: 1.76",
        ".translation-loading",
        ".translation-loading-copy",
        ".translation-pending-context",
        ".translation-pending-commentary",
        ".translation-loading-actions",
        ".translation-loading-actions button",
        ".translation-study-skeleton",
        ".translation-skeleton-block",
        ".translation-skeleton-heading",
        ".translation-skeleton-line",
        ".translation-card.is-loading::before",
        "@keyframes archive-loading-rail",
        "@keyframes archive-review-confirm",
        "@keyframes archive-review-reject",
        "@keyframes archive-sentence-review-confirm",
        "@keyframes archive-sentence-review-reject",
        ".translation-cancelled",
        ".translation-cancelled button",
        ".translation-result.translation-error",
        ".translation-result.translation-cancelled",
        ".translation-unavailable-copy",
        ".translation-recovery-panel",
        ".translation-recovery-panel .translation-runtime-hint",
        ".translation-result.translation-cancelled button",
        ".translation-runtime-hint",
        ".translation-runtime-details",
        ".translation-runtime-details summary",
        ".translation-runtime-details[open] summary",
        ".translation-runtime-command",
        ".translation-runtime-command-row",
        ".translation-runtime-command-row button",
        ".translation-error-actions",
        ".research-card button.is-working",
        ".note-item.is-recent",
        ".note-item.is-recent:focus",
        ".note-item-title",
        ".note-item-title .review-badge",
        ".note-item-title .review-badge.reviewed",
        ".note-danger-actions",
        ".note-danger-actions summary",
        ".note-danger-actions summary::after",
        ".note-danger-actions[open] summary::after",
        ".note-danger-actions button",
        "@keyframes archive-note-highlight",
        ".study-panel-toggle",
        ".study-panel-toggle::before",
        ".study-panel-toggle-action",
        ".study-panel-toggle-summary",
        "text-overflow: ellipsis",
        ".study-page.is-expanded",
        ".study-page.is-dragging",
        ".study-page:not(.is-expanded) .study-tabs",
        "env(safe-area-inset-bottom, 0px)",
        "scroll-padding-top: 112px",
        "scroll-padding-bottom: calc(72px + env(safe-area-inset-bottom, 0px))",
        ".study-page.is-expanded .study-panel-toggle",
        ".study-page.is-expanded .study-panel.active",
        ".study-page.is-expanded .translation-card",
        ".study-page.is-expanded .translation-output",
        "padding-bottom: calc(28px + env(safe-area-inset-bottom, 0px))",
        "overscroll-behavior: contain",
        "touch-action: pan-y",
        "touch-action: none",
        "user-select: none",
        "max(10px, env(safe-area-inset-right, 0px))",
        "max-height: min(72vh, calc(100dvh - 32px))",
        "scroll-margin-block",
        ".sentence-context",
        ".reading-position",
        ".reading-position.is-selectable-cue",
        ".reading-position-main",
        ".reading-position-excerpt",
        ".reading-position button",
        ".reading-position-current",
        ".reader-sentence.reading-cue",
        ".citation-copy-options",
        ".citation-copy-options summary",
        ".citation-copy-options summary::-webkit-details-marker",
        ".citation-copy-options summary::after",
        ".citation-copy-options[open] summary::after",
        ".citation-copy-actions",
        ".note-options",
        ".note-options summary",
        ".note-options summary::-webkit-details-marker",
        ".note-options summary::after",
        ".note-options[open] summary::after",
        ".note-target-tools",
        ".note-target-tools summary",
        ".note-target-tools summary::-webkit-details-marker",
        ".note-target-tools summary::after",
        ".note-target-tools[open] summary::after",
        ".note-target-body",
        ".note-target-preview",
        ".note-target-preview.is-locked",
        ".note-target-lock",
        ".notes-filter-tools",
        ".notes-filter-tools summary",
        ".notes-filter-tools summary::-webkit-details-marker",
        ".notes-filter-tools summary::after",
        ".notes-filter-tools[open] summary::after",
        ".notes-list-tools",
        ".note-filter-clear",
        ".note-list-summary",
        ".notes-list-skeleton",
        ".notes-empty",
        ".notes-empty-actions",
        ".note-target-link",
        ".research-card .sentence-context-item",
        "overscroll-behavior: contain",
        "scrollbar-gutter: stable",
        "@media (min-width: 861px)",
        ".study-page .translation-output",
        "overflow: visible",
        "will-change: transform",
        ".translation-output:focus-visible",
        ".translation-quick-actions",
        ".translation-quick-actions button",
        ".translation-quick-state",
        "@media (prefers-reduced-motion: reduce)",
    ]:
        require_contains(css, needle, "assets/reader-work.css")


def main() -> None:
    check_tokens()
    check_html_entrypoints()
    check_home_css()
    check_home_script()
    check_reader_pages_css()
    check_study_target_ui()
    check_search_ui()
    check_notes_ui()
    check_translations_ui()
    check_study_ui()
    check_work_source_bundle_ui()
    print("layout contracts ok")


if __name__ == "__main__":
    main()
