from __future__ import annotations

import hashlib
import json
import sqlite3
from pathlib import Path
from typing import Any, Mapping


SITE = Path(__file__).resolve().parents[1]
DATA = SITE / "data"

SEGMENT_FILES = {
    "nietzsche": DATA / "nietzsche_segments.jsonl",
    "bible": DATA / "bible_segments.jsonl",
    "kierkegaard": DATA / "kierkegaard_segments.jsonl",
    "wittgenstein": DATA / "wittgenstein_segments.jsonl",
}

SEGMENT_OFFSET_INDEX = DATA / "segment_offset_index.sqlite"
INDEX_SCHEMA_VERSION = 2
BUILD_COMMAND = r"python .\scripts\build_segment_offset_index.py"


class SegmentOffsetIndexError(FileNotFoundError):
    """Raised when the generated byte-offset index cannot be used safely."""


def _index_error(reason: str) -> SegmentOffsetIndexError:
    return SegmentOffsetIndexError(f"{reason}; run {BUILD_COMMAND}")


def source_stat_signature(path: Path) -> tuple[int, int]:
    stat = path.stat()
    return stat.st_size, stat.st_mtime_ns


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _open_read_only(index_path: Path) -> sqlite3.Connection:
    if not index_path.is_file():
        raise _index_error("segment offset index is missing")
    uri = index_path.resolve().as_uri() + "?mode=ro"
    connection: sqlite3.Connection | None = None
    try:
        connection = sqlite3.connect(uri, uri=True, timeout=1.0)
        connection.execute("PRAGMA query_only=ON")
        user_version = int(connection.execute("PRAGMA user_version").fetchone()[0])
        if user_version != INDEX_SCHEMA_VERSION:
            connection.close()
            raise _index_error("segment offset index schema is stale")
        return connection
    except SegmentOffsetIndexError:
        raise
    except sqlite3.DatabaseError as exc:
        if connection is not None:
            connection.close()
        raise _index_error("segment offset index is unreadable") from exc


def _validated_source_metadata(
    connection: sqlite3.Connection,
    corpus_id: str,
    source_path: Path,
) -> tuple[int, int]:
    try:
        row = connection.execute(
            """
            SELECT schema_version, source_name, source_size, source_mtime_ns, source_sha256
            FROM index_sources
            WHERE corpus_id = ?
            """,
            (corpus_id,),
        ).fetchone()
    except sqlite3.DatabaseError as exc:
        raise _index_error("segment offset index schema is invalid") from exc
    if row is None:
        raise _index_error(f"segment offset index has no {corpus_id} source")

    schema_version, source_name, source_size, source_mtime_ns, source_sha256 = row
    if int(schema_version) != INDEX_SCHEMA_VERSION:
        raise _index_error("segment offset index schema is stale")
    if str(source_name) != source_path.name:
        raise _index_error(f"segment offset index source mismatch for {corpus_id}")
    if len(str(source_sha256)) != 64:
        raise _index_error(f"segment offset index signature is invalid for {corpus_id}")

    try:
        current_size, current_mtime_ns = source_stat_signature(source_path)
    except OSError as exc:
        raise FileNotFoundError(f"missing segment file for {corpus_id}") from exc
    if current_size != int(source_size) or current_mtime_ns != int(source_mtime_ns):
        raise _index_error(f"segment offset index is stale for {corpus_id}")
    return current_size, current_mtime_ns


def validate_segment_offset_index(
    index_path: Path = SEGMENT_OFFSET_INDEX,
    segment_files: Mapping[str, Path] | None = None,
    *,
    verify_hashes: bool = False,
) -> dict[str, Any]:
    sources = dict(segment_files or SEGMENT_FILES)
    connection = _open_read_only(index_path)
    try:
        try:
            quick_check = connection.execute("PRAGMA quick_check").fetchone()
            if not quick_check or quick_check[0] != "ok":
                raise _index_error("segment offset index integrity check failed")
            indexed_corpora = {
                str(row[0])
                for row in connection.execute("SELECT corpus_id FROM index_sources ORDER BY corpus_id")
            }
        except sqlite3.DatabaseError as exc:
            raise _index_error("segment offset index schema is invalid") from exc

        expected_corpora = set(sources)
        if indexed_corpora != expected_corpora:
            raise _index_error("segment offset index corpus set is stale")

        counts: dict[str, int] = {}
        for corpus_id, source_path in sources.items():
            _validated_source_metadata(connection, corpus_id, source_path)
            try:
                row = connection.execute(
                    """
                    SELECT source_sha256, record_count
                    FROM index_sources
                    WHERE corpus_id = ?
                    """,
                    (corpus_id,),
                ).fetchone()
                actual_count = int(
                    connection.execute(
                        "SELECT COUNT(*) FROM segment_offsets WHERE corpus_id = ?",
                        (corpus_id,),
                    ).fetchone()[0]
                )
            except sqlite3.DatabaseError as exc:
                raise _index_error("segment offset index schema is invalid") from exc
            if row is None or actual_count != int(row[1]):
                raise _index_error(f"segment offset index count mismatch for {corpus_id}")
            if verify_hashes and sha256_file(source_path) != str(row[0]):
                raise _index_error(f"segment offset index hash is stale for {corpus_id}")
            counts[corpus_id] = actual_count
    finally:
        connection.close()

    return {
        "schema_version": INDEX_SCHEMA_VERSION,
        "records": sum(counts.values()),
        "by_corpus": counts,
        "hashes_verified": verify_hashes,
    }


def resolve_indexed_segment_record(
    corpus_id: str,
    work_id: str,
    segment_id: str,
    variant_id: str = "",
    *,
    index_path: Path = SEGMENT_OFFSET_INDEX,
    segment_files: Mapping[str, Path] | None = None,
) -> dict[str, Any]:
    sources = segment_files or SEGMENT_FILES
    source_path = sources.get(corpus_id)
    if source_path is None:
        raise ValueError(f"unknown corpus_id: {corpus_id}")
    if not source_path.is_file():
        raise FileNotFoundError(f"missing segment file for {corpus_id}")

    connection = _open_read_only(index_path)
    try:
        source_signature = _validated_source_metadata(connection, corpus_id, source_path)
        try:
            if variant_id:
                row = connection.execute(
                    """
                    SELECT byte_offset, byte_length
                    FROM segment_offsets
                    WHERE corpus_id = ? AND work_id = ? AND variant_id = ? AND segment_id = ?
                    """,
                    (corpus_id, work_id, variant_id, segment_id),
                ).fetchone()
            else:
                row = connection.execute(
                    """
                    SELECT byte_offset, byte_length
                    FROM segment_offsets
                    WHERE corpus_id = ? AND work_id = ? AND segment_id = ?
                    ORDER BY record_order
                    LIMIT 1
                    """,
                    (corpus_id, work_id, segment_id),
                ).fetchone()
        except sqlite3.DatabaseError as exc:
            raise _index_error("segment offset index schema is invalid") from exc
    finally:
        connection.close()

    if row is None:
        raise FileNotFoundError(f"segment target not found: {corpus_id}/{work_id}/{variant_id}/{segment_id}")
    byte_offset, byte_length = int(row[0]), int(row[1])
    if byte_offset < 0 or byte_length <= 0:
        raise _index_error(f"segment offset index contains an invalid range for {corpus_id}")

    try:
        with source_path.open("rb") as handle:
            handle.seek(byte_offset)
            raw_record = handle.read(byte_length)
    except OSError as exc:
        raise _index_error(f"segment offset read failed for {corpus_id}") from exc
    if len(raw_record) != byte_length:
        raise _index_error(f"segment offset index range is stale for {corpus_id}")
    try:
        record = json.loads(raw_record.decode("utf-8-sig"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise _index_error(f"segment offset index points to invalid JSON for {corpus_id}") from exc
    if not isinstance(record, dict):
        raise _index_error(f"segment offset index points to a non-object record for {corpus_id}")

    record_key = (
        str(record.get("corpus_id", "")),
        str(record.get("work_id", "")),
        str(record.get("variant_id", "")),
        str(record.get("segment_id", "")),
    )
    expected_variant = variant_id or record_key[2]
    if record_key != (corpus_id, work_id, expected_variant, segment_id):
        raise _index_error(f"segment offset index key mismatch for {corpus_id}")
    try:
        final_source_signature = source_stat_signature(source_path)
    except OSError as exc:
        raise _index_error(f"segment file changed during lookup for {corpus_id}") from exc
    if final_source_signature != source_signature:
        raise _index_error(f"segment file changed during lookup for {corpus_id}")
    return record


def indexed_work_segment_locations(
    corpus_id: str,
    work_id: str,
    variant_id: str = "",
    *,
    index_path: Path = SEGMENT_OFFSET_INDEX,
    segment_files: Mapping[str, Path] | None = None,
) -> list[dict[str, Any]]:
    sources = segment_files or SEGMENT_FILES
    source_path = sources.get(corpus_id)
    if source_path is None:
        raise ValueError(f"unknown corpus_id: {corpus_id}")
    if not source_path.is_file():
        raise FileNotFoundError(f"missing segment file for {corpus_id}")

    connection = _open_read_only(index_path)
    try:
        _validated_source_metadata(connection, corpus_id, source_path)
        try:
            rows = connection.execute(
                """
                SELECT
                  variant_id,
                  segment_id,
                  byte_offset,
                  byte_length,
                  record_order,
                  sentence_count,
                  text_chars
                FROM segment_offsets
                WHERE corpus_id = ? AND work_id = ? AND variant_id = ?
                ORDER BY record_order
                """,
                (corpus_id, work_id, variant_id),
            ).fetchall()
        except sqlite3.DatabaseError as exc:
            raise _index_error("segment offset index schema is invalid") from exc
    finally:
        connection.close()

    if not rows:
        raise FileNotFoundError(f"work segments not found: {corpus_id}/{work_id}/{variant_id}")
    return [
        {
            "corpus_id": corpus_id,
            "work_id": work_id,
            "variant_id": str(row[0]),
            "segment_id": str(row[1]),
            "byte_offset": int(row[2]),
            "byte_length": int(row[3]),
            "record_order": int(row[4]),
            "sentence_count": int(row[5]),
            "text_chars": int(row[6]),
        }
        for row in rows
    ]


def read_indexed_segment_records(
    corpus_id: str,
    locations: list[dict[str, Any]],
    *,
    segment_files: Mapping[str, Path] | None = None,
) -> list[dict[str, Any]]:
    sources = segment_files or SEGMENT_FILES
    source_path = sources.get(corpus_id)
    if source_path is None:
        raise ValueError(f"unknown corpus_id: {corpus_id}")
    if not source_path.is_file():
        raise FileNotFoundError(f"missing segment file for {corpus_id}")
    source_signature = source_stat_signature(source_path)
    records: list[dict[str, Any]] = []

    try:
        with source_path.open("rb") as handle:
            for location in locations:
                byte_offset = int(location["byte_offset"])
                byte_length = int(location["byte_length"])
                if byte_offset < 0 or byte_length <= 0:
                    raise _index_error(f"segment offset index contains an invalid range for {corpus_id}")
                handle.seek(byte_offset)
                raw_record = handle.read(byte_length)
                if len(raw_record) != byte_length:
                    raise _index_error(f"segment offset index range is stale for {corpus_id}")
                try:
                    record = json.loads(raw_record.decode("utf-8-sig"))
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise _index_error(f"segment offset index points to invalid JSON for {corpus_id}") from exc
                if not isinstance(record, dict):
                    raise _index_error(f"segment offset index points to a non-object record for {corpus_id}")
                record_key = (
                    str(record.get("corpus_id", "")),
                    str(record.get("work_id", "")),
                    str(record.get("variant_id", "")),
                    str(record.get("segment_id", "")),
                )
                expected_key = (
                    corpus_id,
                    str(location["work_id"]),
                    str(location["variant_id"]),
                    str(location["segment_id"]),
                )
                if record_key != expected_key:
                    raise _index_error(f"segment offset index key mismatch for {corpus_id}")
                records.append(record)
    except OSError as exc:
        raise _index_error(f"segment offset read failed for {corpus_id}") from exc

    try:
        final_source_signature = source_stat_signature(source_path)
    except OSError as exc:
        raise _index_error(f"segment file changed during lookup for {corpus_id}") from exc
    if final_source_signature != source_signature:
        raise _index_error(f"segment file changed during lookup for {corpus_id}")
    return records
